/**
 * The deck for the writing proof of concept: the 440 kanji Japanese children
 * learn in their first three years at school.
 *
 * Grades 1, 2 and 3 of the 学年別漢字配当表 (kyoiku kanji), exactly 80, 160 and
 * 200 characters. They are listed in learning order, not the ministry's aiueo
 * order: every kanji comes after the deck kanji it is built from (per
 * KanjiVG's decomposition), simplest strokes first among what is available.
 * So 人 and 木 are written before 休, whatever their grades say - grade is
 * kept for grouping, lessons follow this list top to bottom. The order is
 * computed, and stroke-data.spec.ts rejects a kanji placed above its parts.
 *
 * Meanings are kept short on purpose: the prompt has to fit on one line on a
 * phone. They are hand-written per language because no kanji dictionary ships
 * Dutch glosses (KANJIDIC2 has English, French, Spanish and Portuguese only).
 * Readings use the dictionary convention where a dot marks the okurigana
 * boundary.
 *
 * A meaning is the whole question in a review, so when adding kanji:
 *
 * - Pick words that mean one thing on their own. 台 was "standaard", which is
 *   both a stand and a default; it is now "platform, standaard", where the
 *   two senses pin each other down.
 * - Two plain words beat one odd word chosen to dodge a clash, and both
 *   languages get the pair, so they ask the same question: 練 is "train,
 *   drill" and "trainen, drillen", because "train" alone is a locomotive.
 * - Never let two kanji claim the same word, in either language. Write the
 *   sense that separates them instead - 森 is a "woud", 林 a "bos".
 *
 * stroke-data.spec.ts enforces the last rule on the generated file.
 */
export const deck = [
  { kanji: '一', grade: 1, meaning: { en: 'one', nl: 'één' }, on: 'イチ', kun: 'ひと' },
  { kanji: '九', grade: 1, meaning: { en: 'nine', nl: 'negen' }, on: 'キュウ', kun: 'ここの' },
  { kanji: '七', grade: 1, meaning: { en: 'seven', nl: 'zeven' }, on: 'シチ', kun: 'なな' },
  { kanji: '十', grade: 1, meaning: { en: 'ten', nl: 'tien' }, on: 'ジュウ', kun: 'とお' },
  { kanji: '人', grade: 1, meaning: { en: 'person', nl: 'persoon' }, on: 'ジン', kun: 'ひと' },
  { kanji: '二', grade: 1, meaning: { en: 'two', nl: 'twee' }, on: 'ニ', kun: 'ふた' },
  { kanji: '入', grade: 1, meaning: { en: 'enter', nl: 'binnengaan' }, on: 'ニュウ', kun: 'はい.る' },
  { kanji: '八', grade: 1, meaning: { en: 'eight', nl: 'acht' }, on: 'ハチ', kun: 'や.つ' },
  { kanji: '力', grade: 1, meaning: { en: 'power', nl: 'kracht' }, on: 'リョク', kun: 'ちから' },
  { kanji: '刀', grade: 2, meaning: { en: 'sword', nl: 'zwaard' }, on: 'トウ', kun: 'かたな' },
  { kanji: '丁', grade: 3, meaning: { en: 'street block', nl: 'huizenblok' }, on: 'チョウ', kun: '' },
  { kanji: '下', grade: 1, meaning: { en: 'below', nl: 'onder' }, on: 'カ', kun: 'した' },
  { kanji: '口', grade: 1, meaning: { en: 'mouth', nl: 'mond' }, on: 'コウ', kun: 'くち' },
  { kanji: '三', grade: 1, meaning: { en: 'three', nl: 'drie' }, on: 'サン', kun: 'み' },
  { kanji: '山', grade: 1, meaning: { en: 'mountain', nl: 'berg' }, on: 'サン', kun: 'やま' },
  { kanji: '子', grade: 1, meaning: { en: 'child', nl: 'kind' }, on: 'シ', kun: 'こ' },
  { kanji: '女', grade: 1, meaning: { en: 'woman', nl: 'vrouw' }, on: 'ジョ', kun: 'おんな' },
  { kanji: '小', grade: 1, meaning: { en: 'small', nl: 'klein' }, on: 'ショウ', kun: 'ちい.さい' },
  { kanji: '上', grade: 1, meaning: { en: 'above', nl: 'boven' }, on: 'ジョウ', kun: 'うえ' },
  { kanji: '夕', grade: 1, meaning: { en: 'evening', nl: 'avond' }, on: 'セキ', kun: 'ゆう' },
  { kanji: '千', grade: 1, meaning: { en: 'thousand', nl: 'duizend' }, on: 'セン', kun: 'ち' },
  { kanji: '川', grade: 1, meaning: { en: 'river', nl: 'rivier' }, on: 'セン', kun: 'かわ' },
  { kanji: '大', grade: 1, meaning: { en: 'big', nl: 'groot' }, on: 'ダイ', kun: 'おお.きい' },
  { kanji: '土', grade: 1, meaning: { en: 'earth, soil', nl: 'aarde, grond' }, on: 'ド', kun: 'つち' },
  { kanji: '丸', grade: 2, meaning: { en: 'round', nl: 'rond' }, on: 'ガン', kun: 'まる' },
  { kanji: '弓', grade: 2, meaning: { en: 'bow', nl: 'boog' }, on: 'キュウ', kun: 'ゆみ' },
  { kanji: '工', grade: 2, meaning: { en: 'craft, works', nl: 'ambacht' }, on: 'コウ', kun: '' },
  { kanji: '万', grade: 2, meaning: { en: '10,000', nl: 'tienduizend' }, on: 'マン', kun: '' },
  { kanji: '円', grade: 1, meaning: { en: 'circle, yen', nl: 'cirkel, yen' }, on: 'エン', kun: 'まる' },
  { kanji: '王', grade: 1, meaning: { en: 'king', nl: 'koning' }, on: 'オウ', kun: '' },
  { kanji: '火', grade: 1, meaning: { en: 'fire', nl: 'vuur' }, on: 'カ', kun: 'ひ' },
  { kanji: '月', grade: 1, meaning: { en: 'moon, month', nl: 'maan, maand' }, on: 'ゲツ', kun: 'つき' },
  { kanji: '犬', grade: 1, meaning: { en: 'dog', nl: 'hond' }, on: 'ケン', kun: 'いぬ' },
  { kanji: '五', grade: 1, meaning: { en: 'five', nl: 'vijf' }, on: 'ゴ', kun: 'いつ' },
  { kanji: '手', grade: 1, meaning: { en: 'hand', nl: 'hand' }, on: 'シュ', kun: 'て' },
  { kanji: '才', grade: 2, meaning: { en: 'talent', nl: 'talent' }, on: 'サイ', kun: '' },
  { kanji: '水', grade: 1, meaning: { en: 'water', nl: 'water' }, on: 'スイ', kun: 'みず' },
  { kanji: '中', grade: 1, meaning: { en: 'middle, centre', nl: 'midden, centrum' }, on: 'チュウ', kun: 'なか' },
  { kanji: '天', grade: 1, meaning: { en: 'heaven', nl: 'hemel' }, on: 'テン', kun: 'あま' },
  { kanji: '日', grade: 1, meaning: { en: 'day, sun', nl: 'dag, zon' }, on: 'ニチ', kun: 'ひ' },
  { kanji: '文', grade: 1, meaning: { en: 'writing, sentence', nl: 'tekst, zin' }, on: 'ブン', kun: 'ふみ' },
  { kanji: '木', grade: 1, meaning: { en: 'tree, wood', nl: 'boom, hout' }, on: 'モク', kun: 'き' },
  { kanji: '六', grade: 1, meaning: { en: 'six', nl: 'zes' }, on: 'ロク', kun: 'む.つ' },
  { kanji: '引', grade: 2, meaning: { en: 'pull', nl: 'trekken' }, on: 'イン', kun: 'ひ.く' },
  { kanji: '牛', grade: 2, meaning: { en: 'cow', nl: 'koe' }, on: 'ギュウ', kun: 'うし' },
  { kanji: '元', grade: 2, meaning: { en: 'beginning', nl: 'begin' }, on: 'ゲン', kun: 'もと' },
  { kanji: '戸', grade: 2, meaning: { en: 'door', nl: 'deur' }, on: 'コ', kun: 'と' },
  { kanji: '午', grade: 2, meaning: { en: 'midday hour', nl: 'twaalf uur' }, on: 'ゴ', kun: '' },
  { kanji: '公', grade: 2, meaning: { en: 'public', nl: 'openbaar' }, on: 'コウ', kun: '' },
  { kanji: '今', grade: 2, meaning: { en: 'now', nl: 'nu' }, on: 'コン', kun: 'いま' },
  { kanji: '止', grade: 2, meaning: { en: 'stop', nl: 'stoppen' }, on: 'シ', kun: 'と.まる' },
  { kanji: '少', grade: 2, meaning: { en: 'few, little', nl: 'weinig' }, on: 'ショウ', kun: 'すこ.し' },
  { kanji: '心', grade: 2, meaning: { en: 'heart', nl: 'hart' }, on: 'シン', kun: 'こころ' },
  { kanji: '切', grade: 2, meaning: { en: 'cut', nl: 'snijden' }, on: 'セツ', kun: 'き.る' },
  { kanji: '太', grade: 2, meaning: { en: 'thick, fat', nl: 'dik' }, on: 'タイ', kun: 'ふと.い' },
  { kanji: '内', grade: 2, meaning: { en: 'inside', nl: 'binnenkant' }, on: 'ナイ', kun: 'うち' },
  { kanji: '父', grade: 2, meaning: { en: 'father', nl: 'vader' }, on: 'フ', kun: 'ちち' },
  { kanji: '分', grade: 2, meaning: { en: 'divide, minute', nl: 'verdelen, minuut' }, on: 'ブン', kun: 'わ.ける' },
  { kanji: '方', grade: 2, meaning: { en: 'direction', nl: 'richting' }, on: 'ホウ', kun: 'かた' },
  { kanji: '毛', grade: 2, meaning: { en: 'hair, fur', nl: 'haar, vacht' }, on: 'モウ', kun: 'け' },
  { kanji: '友', grade: 2, meaning: { en: 'friend', nl: 'vriend' }, on: 'ユウ', kun: 'とも' },
  { kanji: '化', grade: 3, meaning: { en: 'transform', nl: 'omvormen, veranderen' }, on: 'カ', kun: 'ば.ける' },
  { kanji: '区', grade: 3, meaning: { en: 'ward', nl: 'wijk' }, on: 'ク', kun: '' },
  { kanji: '反', grade: 3, meaning: { en: 'oppose, resist', nl: 'tegenwerken, verzet' }, on: 'ハン', kun: 'そ.る' },
  { kanji: '予', grade: 3, meaning: { en: 'beforehand', nl: 'vooraf' }, on: 'ヨ', kun: '' },
  { kanji: '右', grade: 1, meaning: { en: 'right', nl: 'rechts' }, on: 'ウ', kun: 'みぎ' },
  { kanji: '玉', grade: 1, meaning: { en: 'jewel, ball', nl: 'edelsteen, bal' }, on: 'ギョク', kun: 'たま' },
  { kanji: '左', grade: 1, meaning: { en: 'left', nl: 'links' }, on: 'サ', kun: 'ひだり' },
  { kanji: '四', grade: 1, meaning: { en: 'four', nl: 'vier' }, on: 'シ', kun: 'よ.つ' },
  { kanji: '出', grade: 1, meaning: { en: 'exit, leave', nl: 'uitgaan' }, on: 'シュツ', kun: 'で.る' },
  { kanji: '正', grade: 1, meaning: { en: 'correct', nl: 'juist' }, on: 'セイ', kun: 'ただ.しい' },
  { kanji: '生', grade: 1, meaning: { en: 'life, birth', nl: 'leven, geboorte' }, on: 'セイ', kun: 'い.きる' },
  { kanji: '石', grade: 1, meaning: { en: 'stone', nl: 'steen' }, on: 'セキ', kun: 'いし' },
  { kanji: '田', grade: 1, meaning: { en: 'paddy', nl: 'rijstveld' }, on: 'デン', kun: 'た' },
  { kanji: '白', grade: 1, meaning: { en: 'white', nl: 'wit' }, on: 'ハク', kun: 'しろ.い' },
  { kanji: '本', grade: 1, meaning: { en: 'book, origin', nl: 'boek, oorsprong' }, on: 'ホン', kun: 'もと' },
  { kanji: '目', grade: 1, meaning: { en: 'eye', nl: 'oog' }, on: 'モク', kun: 'め' },
  { kanji: '立', grade: 1, meaning: { en: 'stand up', nl: 'staan, opstaan' }, on: 'リツ', kun: 'た.つ' },
  { kanji: '外', grade: 2, meaning: { en: 'outside', nl: 'buiten' }, on: 'ガイ', kun: 'そと' },
  { kanji: '兄', grade: 2, meaning: { en: 'older brother', nl: 'oudere broer' }, on: 'ケイ', kun: 'あに' },
  { kanji: '古', grade: 2, meaning: { en: 'old', nl: 'oud' }, on: 'コ', kun: 'ふる.い' },
  { kanji: '広', grade: 2, meaning: { en: 'wide', nl: 'breed' }, on: 'コウ', kun: 'ひろ.い' },
  { kanji: '市', grade: 2, meaning: { en: 'city, market', nl: 'stad, markt' }, on: 'シ', kun: 'いち' },
  { kanji: '矢', grade: 2, meaning: { en: 'arrow', nl: 'pijl' }, on: 'シ', kun: 'や' },
  { kanji: '台', grade: 2, meaning: { en: 'platform', nl: 'platform, standaard' }, on: 'ダイ', kun: '' },
  { kanji: '冬', grade: 2, meaning: { en: 'winter', nl: 'winter' }, on: 'トウ', kun: 'ふゆ' },
  { kanji: '半', grade: 2, meaning: { en: 'half', nl: 'half' }, on: 'ハン', kun: 'なか.ば' },
  { kanji: '母', grade: 2, meaning: { en: 'mother', nl: 'moeder' }, on: 'ボ', kun: 'はは' },
  { kanji: '北', grade: 2, meaning: { en: 'north', nl: 'noord' }, on: 'ホク', kun: 'きた' },
  { kanji: '用', grade: 2, meaning: { en: 'use', nl: 'gebruiken' }, on: 'ヨウ', kun: 'もち.いる' },
  { kanji: '央', grade: 3, meaning: { en: 'midpoint', nl: 'middelpunt' }, on: 'オウ', kun: '' },
  { kanji: '去', grade: 3, meaning: { en: 'depart', nl: 'weggaan' }, on: 'キョ', kun: 'さ.る' },
  { kanji: '号', grade: 3, meaning: { en: 'issue, edition', nl: 'editie, uitgave' }, on: 'ゴウ', kun: '' },
  { kanji: '皿', grade: 3, meaning: { en: 'plate', nl: 'bord, schotel' }, on: '', kun: 'さら' },
  { kanji: '仕', grade: 3, meaning: { en: 'serve', nl: 'dienen' }, on: 'シ', kun: 'つか.える' },
  { kanji: '写', grade: 3, meaning: { en: 'copy', nl: 'kopiëren' }, on: 'シャ', kun: 'うつ.す' },
  { kanji: '主', grade: 3, meaning: { en: 'master', nl: 'meester' }, on: 'シュ', kun: 'ぬし' },
  { kanji: '申', grade: 3, meaning: { en: 'report, declare', nl: 'melden, verklaren' }, on: 'シン', kun: 'もう.す' },
  { kanji: '世', grade: 3, meaning: { en: 'world', nl: 'wereld' }, on: 'セ', kun: 'よ' },
  { kanji: '他', grade: 3, meaning: { en: 'other', nl: 'ander' }, on: 'タ', kun: 'ほか' },
  { kanji: '打', grade: 3, meaning: { en: 'beat', nl: 'slaan, meppen' }, on: 'ダ', kun: 'う.つ' },
  { kanji: '代', grade: 3, meaning: { en: 'substitute', nl: 'vervangen' }, on: 'ダイ', kun: 'か.わる' },
  { kanji: '皮', grade: 3, meaning: { en: 'skin', nl: 'huid' }, on: 'ヒ', kun: 'かわ' },
  { kanji: '氷', grade: 3, meaning: { en: 'ice', nl: 'ijs' }, on: 'ヒョウ', kun: 'こおり' },
  { kanji: '平', grade: 3, meaning: { en: 'flat, level', nl: 'plat, effen' }, on: 'ヘイ', kun: 'たい.ら' },
  { kanji: '由', grade: 3, meaning: { en: 'cause', nl: 'oorzaak' }, on: 'ユ', kun: 'よし' },
  { kanji: '礼', grade: 3, meaning: { en: 'courtesy', nl: 'beleefdheid' }, on: 'レイ', kun: '' },
  { kanji: '気', grade: 1, meaning: { en: 'spirit, air', nl: 'geest, stemming' }, on: 'キ', kun: '' },
  { kanji: '休', grade: 1, meaning: { en: 'rest', nl: 'rusten' }, on: 'キュウ', kun: 'やす.む' },
  { kanji: '糸', grade: 1, meaning: { en: 'thread', nl: 'draad' }, on: 'シ', kun: 'いと' },
  { kanji: '字', grade: 1, meaning: { en: 'written character', nl: 'schriftteken' }, on: 'ジ', kun: 'あざ' },
  { kanji: '耳', grade: 1, meaning: { en: 'ear', nl: 'oor' }, on: 'ジ', kun: 'みみ' },
  { kanji: '先', grade: 1, meaning: { en: 'tip, earlier', nl: 'vorig, vooruit' }, on: 'セン', kun: 'さき' },
  { kanji: '早', grade: 1, meaning: { en: 'early', nl: 'vroeg' }, on: 'ソウ', kun: 'はや.い' },
  { kanji: '竹', grade: 1, meaning: { en: 'bamboo', nl: 'bamboe' }, on: 'チク', kun: 'たけ' },
  { kanji: '虫', grade: 1, meaning: { en: 'insect', nl: 'insect' }, on: 'チュウ', kun: 'むし' },
  { kanji: '年', grade: 1, meaning: { en: 'year', nl: 'jaar' }, on: 'ネン', kun: 'とし' },
  { kanji: '百', grade: 1, meaning: { en: 'hundred', nl: 'honderd' }, on: 'ヒャク', kun: '' },
  { kanji: '名', grade: 1, meaning: { en: 'name', nl: 'naam' }, on: 'メイ', kun: 'な' },
  { kanji: '羽', grade: 2, meaning: { en: 'feather, wing', nl: 'veer, vleugel' }, on: 'ウ', kun: 'はね' },
  { kanji: '回', grade: 2, meaning: { en: 'times, revolve', nl: 'keer, draaien' }, on: 'カイ', kun: 'まわ.る' },
  { kanji: '会', grade: 2, meaning: { en: 'meet', nl: 'ontmoeten' }, on: 'カイ', kun: 'あ.う' },
  { kanji: '交', grade: 2, meaning: { en: 'cross, exchange', nl: 'kruisen' }, on: 'コウ', kun: 'まじ.わる' },
  { kanji: '光', grade: 2, meaning: { en: 'light, shine', nl: 'licht' }, on: 'コウ', kun: 'ひかり' },
  { kanji: '考', grade: 2, meaning: { en: 'consider', nl: 'nadenken' }, on: 'コウ', kun: 'かんが.える' },
  { kanji: '行', grade: 2, meaning: { en: 'go', nl: 'gaan' }, on: 'コウ', kun: 'い.く' },
  { kanji: '合', grade: 2, meaning: { en: 'fit, join', nl: 'passen, samen' }, on: 'ゴウ', kun: 'あ.う' },
  { kanji: '寺', grade: 2, meaning: { en: 'temple', nl: 'tempel' }, on: 'ジ', kun: 'てら' },
  { kanji: '自', grade: 2, meaning: { en: 'self, own', nl: 'zelf, eigen' }, on: 'ジ', kun: 'みずか.ら' },
  { kanji: '色', grade: 2, meaning: { en: 'colour', nl: 'kleur' }, on: 'ショク', kun: 'いろ' },
  { kanji: '西', grade: 2, meaning: { en: 'west', nl: 'west' }, on: 'セイ', kun: 'にし' },
  { kanji: '多', grade: 2, meaning: { en: 'many', nl: 'veel' }, on: 'タ', kun: 'おお.い' },
  { kanji: '地', grade: 2, meaning: { en: 'ground', nl: 'bodem, terrein' }, on: 'チ', kun: '' },
  { kanji: '池', grade: 2, meaning: { en: 'pond', nl: 'vijver' }, on: 'チ', kun: 'いけ' },
  { kanji: '当', grade: 2, meaning: { en: 'hit, strike', nl: 'raken, treffen' }, on: 'トウ', kun: 'あ.たる' },
  { kanji: '同', grade: 2, meaning: { en: 'same', nl: 'hetzelfde' }, on: 'ドウ', kun: 'おな.じ' },
  { kanji: '肉', grade: 2, meaning: { en: 'meat', nl: 'vlees' }, on: 'ニク', kun: '' },
  { kanji: '米', grade: 2, meaning: { en: 'rice', nl: 'rijst' }, on: 'ベイ', kun: 'こめ' },
  { kanji: '毎', grade: 2, meaning: { en: 'every', nl: 'elke' }, on: 'マイ', kun: '' },
  { kanji: '安', grade: 3, meaning: { en: 'cheap', nl: 'goedkoop' }, on: 'アン', kun: 'やす.い' },
  { kanji: '曲', grade: 3, meaning: { en: 'melody', nl: 'melodie' }, on: 'キョク', kun: 'ま.がる' },
  { kanji: '血', grade: 3, meaning: { en: 'blood', nl: 'bloed' }, on: 'ケツ', kun: 'ち' },
  { kanji: '向', grade: 3, meaning: { en: 'turn toward', nl: 'toewenden, richten' }, on: 'コウ', kun: 'む.かう' },
  { kanji: '死', grade: 3, meaning: { en: 'die', nl: 'sterven' }, on: 'シ', kun: 'し.ぬ' },
  { kanji: '次', grade: 3, meaning: { en: 'next', nl: 'volgende' }, on: 'ジ', kun: 'つぎ' },
  { kanji: '式', grade: 3, meaning: { en: 'ceremony', nl: 'ceremonie' }, on: 'シキ', kun: '' },
  { kanji: '守', grade: 3, meaning: { en: 'protect', nl: 'beschermen' }, on: 'シュ', kun: 'まも.る' },
  { kanji: '州', grade: 3, meaning: { en: 'province', nl: 'provincie' }, on: 'シュウ', kun: 'す' },
  { kanji: '全', grade: 3, meaning: { en: 'whole', nl: 'geheel' }, on: 'ゼン', kun: 'まった.く' },
  { kanji: '有', grade: 3, meaning: { en: 'have', nl: 'hebben' }, on: 'ユウ', kun: 'あ.る' },
  { kanji: '羊', grade: 3, meaning: { en: 'sheep', nl: 'schaap' }, on: 'ヨウ', kun: 'ひつじ' },
  { kanji: '両', grade: 3, meaning: { en: 'both', nl: 'beide' }, on: 'リョウ', kun: '' },
  { kanji: '列', grade: 3, meaning: { en: 'row', nl: 'rij' }, on: 'レツ', kun: '' },
  { kanji: '花', grade: 1, meaning: { en: 'flower', nl: 'bloem' }, on: 'カ', kun: 'はな' },
  { kanji: '貝', grade: 1, meaning: { en: 'shellfish', nl: 'schelp' }, on: '', kun: 'かい' },
  { kanji: '見', grade: 1, meaning: { en: 'see', nl: 'zien' }, on: 'ケン', kun: 'み.る' },
  { kanji: '車', grade: 1, meaning: { en: 'car, wheel', nl: 'auto, wiel' }, on: 'シャ', kun: 'くるま' },
  { kanji: '赤', grade: 1, meaning: { en: 'red', nl: 'rood' }, on: 'セキ', kun: 'あか' },
  { kanji: '足', grade: 1, meaning: { en: 'foot, leg', nl: 'voet, been' }, on: 'ソク', kun: 'あし' },
  { kanji: '村', grade: 1, meaning: { en: 'village', nl: 'dorp' }, on: 'ソン', kun: 'むら' },
  { kanji: '男', grade: 1, meaning: { en: 'man', nl: 'man' }, on: 'ダン', kun: 'おとこ' },
  { kanji: '町', grade: 1, meaning: { en: 'town', nl: 'stadje' }, on: 'チョウ', kun: 'まち' },
  { kanji: '何', grade: 2, meaning: { en: 'what', nl: 'wat' }, on: 'カ', kun: 'なに' },
  { kanji: '角', grade: 2, meaning: { en: 'corner, horn', nl: 'hoek, hoorn' }, on: 'カク', kun: 'かど' },
  { kanji: '汽', grade: 2, meaning: { en: 'steam', nl: 'stoom' }, on: 'キ', kun: '' },
  { kanji: '近', grade: 2, meaning: { en: 'near', nl: 'dichtbij' }, on: 'キン', kun: 'ちか.い' },
  { kanji: '形', grade: 2, meaning: { en: 'shape', nl: 'vorm' }, on: 'ケイ', kun: 'かたち' },
  { kanji: '言', grade: 2, meaning: { en: 'say', nl: 'zeggen' }, on: 'ゲン', kun: 'い.う' },
  { kanji: '谷', grade: 2, meaning: { en: 'valley', nl: 'vallei' }, on: 'コク', kun: 'たに' },
  { kanji: '作', grade: 2, meaning: { en: 'make', nl: 'maken' }, on: 'サク', kun: 'つく.る' },
  { kanji: '社', grade: 2, meaning: { en: 'company, shrine', nl: 'bedrijf, heiligdom' }, on: 'シャ', kun: 'やしろ' },
  { kanji: '図', grade: 2, meaning: { en: 'diagram, map', nl: 'schema, plattegrond' }, on: 'ズ', kun: 'はか.る' },
  { kanji: '声', grade: 2, meaning: { en: 'voice', nl: 'stem' }, on: 'セイ', kun: 'こえ' },
  { kanji: '走', grade: 2, meaning: { en: 'run', nl: 'rennen' }, on: 'ソウ', kun: 'はし.る' },
  { kanji: '体', grade: 2, meaning: { en: 'body', nl: 'lichaam' }, on: 'タイ', kun: 'からだ' },
  { kanji: '弟', grade: 2, meaning: { en: 'younger brother', nl: 'jongere broer' }, on: 'テイ', kun: 'おとうと' },
  { kanji: '売', grade: 2, meaning: { en: 'sell', nl: 'verkopen' }, on: 'バイ', kun: 'う.る' },
  { kanji: '麦', grade: 2, meaning: { en: 'wheat', nl: 'tarwe' }, on: 'バク', kun: 'むぎ' },
  { kanji: '来', grade: 2, meaning: { en: 'come', nl: 'komen' }, on: 'ライ', kun: 'く.る' },
  { kanji: '里', grade: 2, meaning: { en: 'hometown', nl: 'geboortedorp' }, on: 'リ', kun: 'さと' },
  { kanji: '医', grade: 3, meaning: { en: 'doctor', nl: 'dokter' }, on: 'イ', kun: '' },
  { kanji: '究', grade: 3, meaning: { en: 'research', nl: 'onderzoek' }, on: 'キュウ', kun: 'きわ.める' },
  { kanji: '局', grade: 3, meaning: { en: 'bureau, office', nl: 'bureau, kantoor' }, on: 'キョク', kun: '' },
  { kanji: '君', grade: 3, meaning: { en: 'you', nl: 'jij' }, on: 'クン', kun: 'きみ' },
  { kanji: '決', grade: 3, meaning: { en: 'decide', nl: 'beslissen' }, on: 'ケツ', kun: 'き.める' },
  { kanji: '住', grade: 3, meaning: { en: 'reside', nl: 'wonen' }, on: 'ジュウ', kun: 'す.む' },
  { kanji: '助', grade: 3, meaning: { en: 'help', nl: 'helpen' }, on: 'ジョ', kun: 'たす.ける' },
  { kanji: '身', grade: 3, meaning: { en: 'physique, stature', nl: 'lijf, gestalte' }, on: 'シン', kun: 'み' },
  { kanji: '対', grade: 3, meaning: { en: 'versus', nl: 'tegenover' }, on: 'タイ', kun: '' },
  { kanji: '投', grade: 3, meaning: { en: 'throw', nl: 'gooien' }, on: 'トウ', kun: 'な.げる' },
  { kanji: '豆', grade: 3, meaning: { en: 'bean', nl: 'boon' }, on: 'トウ', kun: 'まめ' },
  { kanji: '坂', grade: 3, meaning: { en: 'slope', nl: 'helling' }, on: 'ハン', kun: 'さか' },
  { kanji: '返', grade: 3, meaning: { en: 'give back', nl: 'teruggeven' }, on: 'ヘン', kun: 'かえ.す' },
  { kanji: '役', grade: 3, meaning: { en: 'role, duty', nl: 'rol, functie' }, on: 'ヤク', kun: '' },
  { kanji: '雨', grade: 1, meaning: { en: 'rain', nl: 'regen' }, on: 'ウ', kun: 'あめ' },
  { kanji: '学', grade: 1, meaning: { en: 'study', nl: 'leren' }, on: 'ガク', kun: 'まな.ぶ' },
  { kanji: '金', grade: 1, meaning: { en: 'gold, money', nl: 'goud, geld' }, on: 'キン', kun: 'かね' },
  { kanji: '空', grade: 1, meaning: { en: 'sky, empty', nl: 'lucht, leeg' }, on: 'クウ', kun: 'そら' },
  { kanji: '青', grade: 1, meaning: { en: 'blue', nl: 'blauw' }, on: 'セイ', kun: 'あお' },
  { kanji: '林', grade: 1, meaning: { en: 'woods', nl: 'bos' }, on: 'リン', kun: 'はやし' },
  { kanji: '画', grade: 2, meaning: { en: 'image, stroke', nl: 'beeld, streek' }, on: 'ガ', kun: '' },
  { kanji: '岩', grade: 2, meaning: { en: 'rock', nl: 'rots' }, on: 'ガン', kun: 'いわ' },
  { kanji: '京', grade: 2, meaning: { en: 'capital', nl: 'hoofdstad' }, on: 'キョウ', kun: '' },
  { kanji: '国', grade: 2, meaning: { en: 'country', nl: 'land' }, on: 'コク', kun: 'くに' },
  { kanji: '姉', grade: 2, meaning: { en: 'older sister', nl: 'oudere zus' }, on: 'シ', kun: 'あね' },
  { kanji: '知', grade: 2, meaning: { en: 'know', nl: 'weten' }, on: 'チ', kun: 'し.る' },
  { kanji: '長', grade: 2, meaning: { en: 'long, chief', nl: 'lang, leider' }, on: 'チョウ', kun: 'なが.い' },
  { kanji: '直', grade: 2, meaning: { en: 'straight, fix', nl: 'recht, herstellen' }, on: 'チョク', kun: 'なお.す' },
  { kanji: '店', grade: 2, meaning: { en: 'shop', nl: 'winkel' }, on: 'テン', kun: 'みせ' },
  { kanji: '東', grade: 2, meaning: { en: 'east', nl: 'oost' }, on: 'トウ', kun: 'ひがし' },
  { kanji: '歩', grade: 2, meaning: { en: 'walk', nl: 'lopen' }, on: 'ホ', kun: 'ある.く' },
  { kanji: '妹', grade: 2, meaning: { en: 'younger sister', nl: 'jongere zus' }, on: 'マイ', kun: 'いもうと' },
  { kanji: '明', grade: 2, meaning: { en: 'bright', nl: 'helder' }, on: 'メイ', kun: 'あか.るい' },
  { kanji: '門', grade: 2, meaning: { en: 'gate', nl: 'poort' }, on: 'モン', kun: 'かど' },
  { kanji: '夜', grade: 2, meaning: { en: 'night', nl: 'nacht' }, on: 'ヤ', kun: 'よる' },
  { kanji: '委', grade: 3, meaning: { en: 'entrust', nl: 'toevertrouwen' }, on: 'イ', kun: 'ゆだ.ねる' },
  { kanji: '育', grade: 3, meaning: { en: 'nurture', nl: 'opvoeden' }, on: 'イク', kun: 'そだ.てる' },
  { kanji: '泳', grade: 3, meaning: { en: 'swim', nl: 'zwemmen' }, on: 'エイ', kun: 'およ.ぐ' },
  { kanji: '岸', grade: 3, meaning: { en: 'shore', nl: 'oever' }, on: 'ガン', kun: 'きし' },
  { kanji: '苦', grade: 3, meaning: { en: 'bitter, painful', nl: 'bitter, pijnlijk' }, on: 'ク', kun: 'くる.しい' },
  { kanji: '具', grade: 3, meaning: { en: 'tool', nl: 'gereedschap' }, on: 'グ', kun: '' },
  { kanji: '幸', grade: 3, meaning: { en: 'happiness', nl: 'geluk' }, on: 'コウ', kun: 'しあわ.せ' },
  { kanji: '使', grade: 3, meaning: { en: 'employ', nl: 'inzetten, benutten' }, on: 'シ', kun: 'つか.う' },
  { kanji: '始', grade: 3, meaning: { en: 'start', nl: 'starten' }, on: 'シ', kun: 'はじ.める' },
  { kanji: '事', grade: 3, meaning: { en: 'matter, affair', nl: 'zaak, kwestie' }, on: 'ジ', kun: 'こと' },
  { kanji: '実', grade: 3, meaning: { en: 'fruit', nl: 'vrucht' }, on: 'ジツ', kun: 'み' },
  { kanji: '者', grade: 3, meaning: { en: 'someone', nl: 'iemand' }, on: 'シャ', kun: 'もの' },
  { kanji: '取', grade: 3, meaning: { en: 'take', nl: 'nemen' }, on: 'シュ', kun: 'と.る' },
  { kanji: '受', grade: 3, meaning: { en: 'receive', nl: 'ontvangen' }, on: 'ジュ', kun: 'う.ける' },
  { kanji: '所', grade: 3, meaning: { en: 'spot, location', nl: 'plek, locatie' }, on: 'ショ', kun: 'ところ' },
  { kanji: '昔', grade: 3, meaning: { en: 'antiquity', nl: 'oudheid' }, on: 'セキ', kun: 'むかし' },
  { kanji: '注', grade: 3, meaning: { en: 'pour', nl: 'gieten' }, on: 'チュウ', kun: 'そそ.ぐ' },
  { kanji: '定', grade: 3, meaning: { en: 'determine', nl: 'bepalen' }, on: 'テイ', kun: 'さだ.める' },
  { kanji: '波', grade: 3, meaning: { en: 'wave, ripple', nl: 'golf, deining' }, on: 'ハ', kun: 'なみ' },
  { kanji: '板', grade: 3, meaning: { en: 'plank', nl: 'plank' }, on: 'ハン', kun: 'いた' },
  { kanji: '表', grade: 3, meaning: { en: 'surface', nl: 'oppervlak' }, on: 'ヒョウ', kun: 'おもて' },
  { kanji: '服', grade: 3, meaning: { en: 'clothes', nl: 'kleren' }, on: 'フク', kun: '' },
  { kanji: '物', grade: 3, meaning: { en: 'thing', nl: 'ding' }, on: 'ブツ', kun: 'もの' },
  { kanji: '放', grade: 3, meaning: { en: 'release', nl: 'loslaten' }, on: 'ホウ', kun: 'はな.す' },
  { kanji: '味', grade: 3, meaning: { en: 'taste', nl: 'smaak' }, on: 'ミ', kun: 'あじ' },
  { kanji: '命', grade: 3, meaning: { en: 'lifespan', nl: 'levensduur' }, on: 'メイ', kun: 'いのち' },
  { kanji: '油', grade: 3, meaning: { en: 'oil', nl: 'olie' }, on: 'ユ', kun: 'あぶら' },
  { kanji: '和', grade: 3, meaning: { en: 'harmony', nl: 'harmonie' }, on: 'ワ', kun: 'やわ.らぐ' },
  { kanji: '音', grade: 1, meaning: { en: 'sound', nl: 'geluid' }, on: 'オン', kun: 'おと' },
  { kanji: '草', grade: 1, meaning: { en: 'grass', nl: 'gras' }, on: 'ソウ', kun: 'くさ' },
  { kanji: '科', grade: 2, meaning: { en: 'course, section', nl: 'vak, afdeling' }, on: 'カ', kun: '' },
  { kanji: '海', grade: 2, meaning: { en: 'sea', nl: 'zee' }, on: 'カイ', kun: 'うみ' },
  { kanji: '活', grade: 2, meaning: { en: 'lively, activity', nl: 'activiteit' }, on: 'カツ', kun: '' },
  { kanji: '計', grade: 2, meaning: { en: 'measure, plan', nl: 'meten, plan' }, on: 'ケイ', kun: 'はか.る' },
  { kanji: '後', grade: 2, meaning: { en: 'after, behind', nl: 'na, achter' }, on: 'ゴ', kun: 'あと' },
  { kanji: '思', grade: 2, meaning: { en: 'think, feel', nl: 'denken, vinden' }, on: 'シ', kun: 'おも.う' },
  { kanji: '室', grade: 2, meaning: { en: 'room', nl: 'kamer' }, on: 'シツ', kun: 'むろ' },
  { kanji: '首', grade: 2, meaning: { en: 'neck', nl: 'nek' }, on: 'シュ', kun: 'くび' },
  { kanji: '秋', grade: 2, meaning: { en: 'autumn', nl: 'herfst' }, on: 'シュウ', kun: 'あき' },
  { kanji: '春', grade: 2, meaning: { en: 'spring', nl: 'lente' }, on: 'シュン', kun: 'はる' },
  { kanji: '食', grade: 2, meaning: { en: 'eat, food', nl: 'eten' }, on: 'ショク', kun: 'た.べる' },
  { kanji: '星', grade: 2, meaning: { en: 'star', nl: 'ster' }, on: 'セイ', kun: 'ほし' },
  { kanji: '前', grade: 2, meaning: { en: 'front, before', nl: 'voor, voorkant' }, on: 'ゼン', kun: 'まえ' },
  { kanji: '茶', grade: 2, meaning: { en: 'tea', nl: 'thee' }, on: 'チャ', kun: '' },
  { kanji: '昼', grade: 2, meaning: { en: 'daytime', nl: 'middag, overdag' }, on: 'チュウ', kun: 'ひる' },
  { kanji: '点', grade: 2, meaning: { en: 'point, dot', nl: 'punt' }, on: 'テン', kun: '' },
  { kanji: '南', grade: 2, meaning: { en: 'south', nl: 'zuid' }, on: 'ナン', kun: 'みなみ' },
  { kanji: '風', grade: 2, meaning: { en: 'wind', nl: 'wind' }, on: 'フウ', kun: 'かぜ' },
  { kanji: '屋', grade: 3, meaning: { en: 'roof', nl: 'dak' }, on: 'オク', kun: 'や' },
  { kanji: '界', grade: 3, meaning: { en: 'boundary', nl: 'grens' }, on: 'カイ', kun: '' },
  { kanji: '客', grade: 3, meaning: { en: 'guest', nl: 'gast' }, on: 'キャク', kun: '' },
  { kanji: '急', grade: 3, meaning: { en: 'hurry', nl: 'haasten' }, on: 'キュウ', kun: 'いそ.ぐ' },
  { kanji: '級', grade: 3, meaning: { en: 'rank, class', nl: 'rang, klas' }, on: 'キュウ', kun: '' },
  { kanji: '係', grade: 3, meaning: { en: 'attendant, official', nl: 'beambte, opzichter' }, on: 'ケイ', kun: 'かかり' },
  { kanji: '研', grade: 3, meaning: { en: 'sharpen', nl: 'slijpen' }, on: 'ケン', kun: 'と.ぐ' },
  { kanji: '県', grade: 3, meaning: { en: 'prefecture', nl: 'prefectuur' }, on: 'ケン', kun: '' },
  { kanji: '指', grade: 3, meaning: { en: 'finger', nl: 'vinger' }, on: 'シ', kun: 'ゆび' },
  { kanji: '持', grade: 3, meaning: { en: 'hold', nl: 'vasthouden' }, on: 'ジ', kun: 'も.つ' },
  { kanji: '拾', grade: 3, meaning: { en: 'retrieve', nl: 'oprapen' }, on: 'シュウ', kun: 'ひろ.う' },
  { kanji: '重', grade: 3, meaning: { en: 'heavy', nl: 'zwaar' }, on: 'ジュウ', kun: 'おも.い' },
  { kanji: '昭', grade: 3, meaning: { en: 'radiant', nl: 'stralend' }, on: 'ショウ', kun: '' },
  { kanji: '乗', grade: 3, meaning: { en: 'ride, board', nl: 'instappen, berijden' }, on: 'ジョウ', kun: 'の.る' },
  { kanji: '神', grade: 3, meaning: { en: 'god', nl: 'god' }, on: 'シン', kun: 'かみ' },
  { kanji: '相', grade: 3, meaning: { en: 'mutual', nl: 'wederzijds' }, on: 'ソウ', kun: 'あい' },
  { kanji: '送', grade: 3, meaning: { en: 'send', nl: 'sturen' }, on: 'ソウ', kun: 'おく.る' },
  { kanji: '待', grade: 3, meaning: { en: 'wait', nl: 'wachten' }, on: 'タイ', kun: 'ま.つ' },
  { kanji: '炭', grade: 3, meaning: { en: 'charcoal', nl: 'houtskool' }, on: 'タン', kun: 'すみ' },
  { kanji: '柱', grade: 3, meaning: { en: 'pillar', nl: 'pilaar' }, on: 'チュウ', kun: 'はしら' },
  { kanji: '追', grade: 3, meaning: { en: 'chase', nl: 'achtervolgen' }, on: 'ツイ', kun: 'お.う' },
  { kanji: '度', grade: 3, meaning: { en: 'degree', nl: 'graad' }, on: 'ド', kun: 'たび' },
  { kanji: '畑', grade: 3, meaning: { en: 'cropland, farmland', nl: 'akker, bouwland' }, on: '', kun: 'はたけ' },
  { kanji: '発', grade: 3, meaning: { en: 'set off, departure', nl: 'afreizen, vertrek' }, on: 'ハツ', kun: '' },
  { kanji: '美', grade: 3, meaning: { en: 'beautiful', nl: 'mooi' }, on: 'ビ', kun: 'うつく.しい' },
  { kanji: '秒', grade: 3, meaning: { en: 'second', nl: 'seconde' }, on: 'ビョウ', kun: '' },
  { kanji: '品', grade: 3, meaning: { en: 'goods', nl: 'waren' }, on: 'ヒン', kun: 'しな' },
  { kanji: '負', grade: 3, meaning: { en: 'lose', nl: 'verliezen' }, on: 'フ', kun: 'ま.ける' },
  { kanji: '面', grade: 3, meaning: { en: 'plane, facet', nl: 'vlak, facet' }, on: 'メン', kun: '' },
  { kanji: '洋', grade: 3, meaning: { en: 'ocean', nl: 'oceaan' }, on: 'ヨウ', kun: '' },
  { kanji: '校', grade: 1, meaning: { en: 'school', nl: 'school' }, on: 'コウ', kun: '' },
  { kanji: '夏', grade: 2, meaning: { en: 'summer', nl: 'zomer' }, on: 'カ', kun: 'なつ' },
  { kanji: '家', grade: 2, meaning: { en: 'house, family', nl: 'huis, gezin' }, on: 'カ', kun: 'いえ' },
  { kanji: '記', grade: 2, meaning: { en: 'record, note', nl: 'opschrijven' }, on: 'キ', kun: 'しる.す' },
  { kanji: '帰', grade: 2, meaning: { en: 'return home', nl: 'terugkeren' }, on: 'キ', kun: 'かえ.る' },
  { kanji: '原', grade: 2, meaning: { en: 'plain', nl: 'vlakte' }, on: 'ゲン', kun: 'はら' },
  { kanji: '高', grade: 2, meaning: { en: 'high, tall', nl: 'hoog' }, on: 'コウ', kun: 'たか.い' },
  { kanji: '紙', grade: 2, meaning: { en: 'paper', nl: 'papier' }, on: 'シ', kun: 'かみ' },
  { kanji: '時', grade: 2, meaning: { en: 'time', nl: 'tijd' }, on: 'ジ', kun: 'とき' },
  { kanji: '弱', grade: 2, meaning: { en: 'weak', nl: 'zwak' }, on: 'ジャク', kun: 'よわ.い' },
  { kanji: '書', grade: 2, meaning: { en: 'write', nl: 'schrijven' }, on: 'ショ', kun: 'か.く' },
  { kanji: '通', grade: 2, meaning: { en: 'pass through', nl: 'doorgaan' }, on: 'ツウ', kun: 'とお.る' },
  { kanji: '馬', grade: 2, meaning: { en: 'horse', nl: 'paard' }, on: 'バ', kun: 'うま' },
  { kanji: '員', grade: 3, meaning: { en: 'member, staff', nl: 'lid, personeelslid' }, on: 'イン', kun: '' },
  { kanji: '院', grade: 3, meaning: { en: 'institution', nl: 'instituut' }, on: 'イン', kun: '' },
  { kanji: '荷', grade: 3, meaning: { en: 'luggage', nl: 'bagage' }, on: 'カ', kun: 'に' },
  { kanji: '起', grade: 3, meaning: { en: 'wake', nl: 'ontwaken' }, on: 'キ', kun: 'お.きる' },
  { kanji: '宮', grade: 3, meaning: { en: 'palace', nl: 'paleis' }, on: 'キュウ', kun: 'みや' },
  { kanji: '庫', grade: 3, meaning: { en: 'warehouse', nl: 'magazijn' }, on: 'コ', kun: '' },
  { kanji: '根', grade: 3, meaning: { en: 'root, base', nl: 'wortel, basis' }, on: 'コン', kun: 'ね' },
  { kanji: '酒', grade: 3, meaning: { en: 'alcohol, sake', nl: 'drank, sake' }, on: 'シュ', kun: 'さけ' },
  { kanji: '消', grade: 3, meaning: { en: 'vanish', nl: 'verdwijnen' }, on: 'ショウ', kun: 'き.える' },
  { kanji: '真', grade: 3, meaning: { en: 'truth', nl: 'waarheid' }, on: 'シン', kun: 'ま' },
  { kanji: '息', grade: 3, meaning: { en: 'breath', nl: 'adem' }, on: 'ソク', kun: 'いき' },
  { kanji: '速', grade: 3, meaning: { en: 'fast', nl: 'snel' }, on: 'ソク', kun: 'はや.い' },
  { kanji: '庭', grade: 3, meaning: { en: 'yard, courtyard', nl: 'erf, achtertuin' }, on: 'テイ', kun: 'にわ' },
  { kanji: '配', grade: 3, meaning: { en: 'distribute', nl: 'uitdelen' }, on: 'ハイ', kun: 'くば.る' },
  { kanji: '倍', grade: 3, meaning: { en: 'double', nl: 'dubbel' }, on: 'バイ', kun: '' },
  { kanji: '病', grade: 3, meaning: { en: 'illness', nl: 'ziekte' }, on: 'ビョウ', kun: 'や.む' },
  { kanji: '勉', grade: 3, meaning: { en: 'diligence, effort', nl: 'vlijt, ijver' }, on: 'ベン', kun: '' },
  { kanji: '流', grade: 3, meaning: { en: 'flow', nl: 'stromen' }, on: 'リュウ', kun: 'なが.れる' },
  { kanji: '旅', grade: 3, meaning: { en: 'travel', nl: 'reizen' }, on: 'リョ', kun: 'たび' },
  { kanji: '魚', grade: 2, meaning: { en: 'fish', nl: 'vis' }, on: 'ギョ', kun: 'さかな' },
  { kanji: '強', grade: 2, meaning: { en: 'strong', nl: 'sterk' }, on: 'キョウ', kun: 'つよ.い' },
  { kanji: '教', grade: 2, meaning: { en: 'teach', nl: 'onderwijzen' }, on: 'キョウ', kun: 'おし.える' },
  { kanji: '黄', grade: 2, meaning: { en: 'yellow', nl: 'geel' }, on: 'コウ', kun: 'き' },
  { kanji: '黒', grade: 2, meaning: { en: 'black', nl: 'zwart' }, on: 'コク', kun: 'くろ' },
  { kanji: '細', grade: 2, meaning: { en: 'thin, fine', nl: 'dun, fijn' }, on: 'サイ', kun: 'ほそ.い' },
  { kanji: '週', grade: 2, meaning: { en: 'week', nl: 'week' }, on: 'シュウ', kun: '' },
  { kanji: '雪', grade: 2, meaning: { en: 'snow', nl: 'sneeuw' }, on: 'セツ', kun: 'ゆき' },
  { kanji: '船', grade: 2, meaning: { en: 'ship', nl: 'schip' }, on: 'セン', kun: 'ふね' },
  { kanji: '組', grade: 2, meaning: { en: 'group, assemble', nl: 'groep, samenstellen' }, on: 'ソ', kun: 'く.む' },
  { kanji: '鳥', grade: 2, meaning: { en: 'bird', nl: 'vogel' }, on: 'チョウ', kun: 'とり' },
  { kanji: '島', grade: 3, meaning: { en: 'island', nl: 'eiland' }, on: 'トウ', kun: 'しま' },
  { kanji: '野', grade: 2, meaning: { en: 'field', nl: 'veld' }, on: 'ヤ', kun: 'の' },
  { kanji: '理', grade: 2, meaning: { en: 'reason, logic', nl: 'rede, logica' }, on: 'リ', kun: '' },
  { kanji: '悪', grade: 3, meaning: { en: 'bad', nl: 'slecht' }, on: 'アク', kun: 'わる.い' },
  { kanji: '球', grade: 3, meaning: { en: 'sphere, globe', nl: 'bol, globe' }, on: 'キュウ', kun: 'たま' },
  { kanji: '祭', grade: 3, meaning: { en: 'festival', nl: 'festival' }, on: 'サイ', kun: 'まつ.り' },
  { kanji: '終', grade: 3, meaning: { en: 'finish', nl: 'eindigen' }, on: 'シュウ', kun: 'お.わる' },
  { kanji: '習', grade: 3, meaning: { en: 'practise', nl: 'oefenen' }, on: 'シュウ', kun: 'なら.う' },
  { kanji: '宿', grade: 3, meaning: { en: 'inn', nl: 'herberg' }, on: 'シュク', kun: 'やど' },
  { kanji: '商', grade: 3, meaning: { en: 'commerce', nl: 'handel' }, on: 'ショウ', kun: 'あきな.う' },
  { kanji: '章', grade: 3, meaning: { en: 'chapter', nl: 'hoofdstuk' }, on: 'ショウ', kun: '' },
  { kanji: '深', grade: 3, meaning: { en: 'deep', nl: 'diep' }, on: 'シン', kun: 'ふか.い' },
  { kanji: '進', grade: 3, meaning: { en: 'advance', nl: 'vooruitgaan' }, on: 'シン', kun: 'すす.む' },
  { kanji: '族', grade: 3, meaning: { en: 'tribe, clan', nl: 'stam, volksgroep' }, on: 'ゾク', kun: '' },
  { kanji: '第', grade: 3, meaning: { en: 'ordinal prefix', nl: 'rangtelwoord' }, on: 'ダイ', kun: '' },
  { kanji: '帳', grade: 3, meaning: { en: 'notebook', nl: 'schrift, kladblok' }, on: 'チョウ', kun: '' },
  { kanji: '笛', grade: 3, meaning: { en: 'flute', nl: 'fluit' }, on: 'テキ', kun: 'ふえ' },
  { kanji: '転', grade: 3, meaning: { en: 'roll', nl: 'rollen' }, on: 'テン', kun: 'ころ.がる' },
  { kanji: '都', grade: 3, meaning: { en: 'metropolis', nl: 'metropool' }, on: 'ト', kun: 'みやこ' },
  { kanji: '動', grade: 3, meaning: { en: 'move', nl: 'bewegen' }, on: 'ドウ', kun: 'うご.く' },
  { kanji: '部', grade: 3, meaning: { en: 'part, division', nl: 'deel, onderdeel' }, on: 'ブ', kun: '' },
  { kanji: '問', grade: 3, meaning: { en: 'question', nl: 'vraag' }, on: 'モン', kun: 'と.う' },
  { kanji: '森', grade: 1, meaning: { en: 'forest', nl: 'woud' }, on: 'シン', kun: 'もり' },
  { kanji: '雲', grade: 2, meaning: { en: 'cloud', nl: 'wolk' }, on: 'ウン', kun: 'くも' },
  { kanji: '絵', grade: 2, meaning: { en: 'drawing', nl: 'tekening' }, on: 'カイ', kun: 'え' },
  { kanji: '間', grade: 2, meaning: { en: 'interval, between', nl: 'tussen, interval' }, on: 'カン', kun: 'あいだ' },
  { kanji: '場', grade: 2, meaning: { en: 'place', nl: 'plaats' }, on: 'ジョウ', kun: 'ば' },
  { kanji: '晴', grade: 2, meaning: { en: 'clear weather', nl: 'opklaren' }, on: 'セイ', kun: 'は.れる' },
  { kanji: '朝', grade: 2, meaning: { en: 'morning', nl: 'ochtend' }, on: 'チョウ', kun: 'あさ' },
  { kanji: '答', grade: 2, meaning: { en: 'answer', nl: 'antwoord' }, on: 'トウ', kun: 'こた.える' },
  { kanji: '道', grade: 2, meaning: { en: 'road, way', nl: 'weg' }, on: 'ドウ', kun: 'みち' },
  { kanji: '買', grade: 2, meaning: { en: 'buy', nl: 'kopen' }, on: 'バイ', kun: 'か.う' },
  { kanji: '番', grade: 2, meaning: { en: 'number in order', nl: 'beurt, nummer' }, on: 'バン', kun: '' },
  { kanji: '飲', grade: 3, meaning: { en: 'drink', nl: 'drinken' }, on: 'イン', kun: 'の.む' },
  { kanji: '運', grade: 3, meaning: { en: 'carry', nl: 'vervoeren' }, on: 'ウン', kun: 'はこ.ぶ' },
  { kanji: '温', grade: 3, meaning: { en: 'warm', nl: 'warm' }, on: 'オン', kun: 'あたた.かい' },
  { kanji: '開', grade: 3, meaning: { en: 'open', nl: 'openen' }, on: 'カイ', kun: 'ひら.く' },
  { kanji: '階', grade: 3, meaning: { en: 'storey', nl: 'verdieping' }, on: 'カイ', kun: '' },
  { kanji: '寒', grade: 3, meaning: { en: 'cold', nl: 'koud' }, on: 'カン', kun: 'さむ.い' },
  { kanji: '期', grade: 3, meaning: { en: 'period', nl: 'periode' }, on: 'キ', kun: '' },
  { kanji: '軽', grade: 3, meaning: { en: 'lightweight', nl: 'lichtgewicht' }, on: 'ケイ', kun: 'かる.い' },
  { kanji: '湖', grade: 3, meaning: { en: 'lake', nl: 'meer, plas' }, on: 'コ', kun: 'みずうみ' },
  { kanji: '港', grade: 3, meaning: { en: 'harbour', nl: 'haven' }, on: 'コウ', kun: 'みなと' },
  { kanji: '歯', grade: 3, meaning: { en: 'tooth', nl: 'tand' }, on: 'シ', kun: 'は' },
  { kanji: '集', grade: 3, meaning: { en: 'gather', nl: 'verzamelen' }, on: 'シュウ', kun: 'あつ.める' },
  { kanji: '暑', grade: 3, meaning: { en: 'sweltering', nl: 'snikheet' }, on: 'ショ', kun: 'あつ.い' },
  { kanji: '勝', grade: 3, meaning: { en: 'win', nl: 'winnen' }, on: 'ショウ', kun: 'か.つ' },
  { kanji: '植', grade: 3, meaning: { en: 'plant', nl: 'planten' }, on: 'ショク', kun: 'う.える' },
  { kanji: '短', grade: 3, meaning: { en: 'short', nl: 'kort' }, on: 'タン', kun: 'みじか.い' },
  { kanji: '着', grade: 3, meaning: { en: 'wear', nl: 'aantrekken' }, on: 'チャク', kun: 'き.る' },
  { kanji: '湯', grade: 3, meaning: { en: 'hot bath, bathwater', nl: 'heet bad, badwater' }, on: 'トウ', kun: 'ゆ' },
  { kanji: '登', grade: 3, meaning: { en: 'climb', nl: 'klimmen' }, on: 'トウ', kun: 'のぼ.る' },
  { kanji: '等', grade: 3, meaning: { en: 'equal', nl: 'gelijk' }, on: 'トウ', kun: 'ひと.しい' },
  { kanji: '童', grade: 3, meaning: { en: 'youngster, juvenile', nl: 'jochie, jongeling' }, on: 'ドウ', kun: 'わらべ' },
  { kanji: '悲', grade: 3, meaning: { en: 'sad', nl: 'verdrietig' }, on: 'ヒ', kun: 'かな.しい' },
  { kanji: '筆', grade: 3, meaning: { en: 'brush', nl: 'penseel' }, on: 'ヒツ', kun: 'ふで' },
  { kanji: '遊', grade: 3, meaning: { en: 'play', nl: 'spelen' }, on: 'ユウ', kun: 'あそ.ぶ' },
  { kanji: '葉', grade: 3, meaning: { en: 'leaf, foliage', nl: 'blad, loof' }, on: 'ヨウ', kun: 'は' },
  { kanji: '陽', grade: 3, meaning: { en: 'sunshine', nl: 'zonneschijn' }, on: 'ヨウ', kun: '' },
  { kanji: '落', grade: 3, meaning: { en: 'fall', nl: 'vallen' }, on: 'ラク', kun: 'お.ちる' },
  { kanji: '園', grade: 2, meaning: { en: 'garden, park', nl: 'tuin, park' }, on: 'エン', kun: 'その' },
  { kanji: '遠', grade: 2, meaning: { en: 'far', nl: 'ver' }, on: 'エン', kun: 'とお.い' },
  { kanji: '楽', grade: 2, meaning: { en: 'fun, music', nl: 'plezier, muziek' }, on: 'ガク', kun: 'たの.しい' },
  { kanji: '新', grade: 2, meaning: { en: 'new', nl: 'nieuw' }, on: 'シン', kun: 'あたら.しい' },
  { kanji: '数', grade: 2, meaning: { en: 'count, figures', nl: 'aantal, tellen' }, on: 'スウ', kun: 'かず' },
  { kanji: '電', grade: 2, meaning: { en: 'electricity', nl: 'elektriciteit' }, on: 'デン', kun: '' },
  { kanji: '話', grade: 2, meaning: { en: 'talk, story', nl: 'praten, verhaal' }, on: 'ワ', kun: 'はな.す' },
  { kanji: '暗', grade: 3, meaning: { en: 'dark', nl: 'donker' }, on: 'アン', kun: 'くら.い' },
  { kanji: '意', grade: 3, meaning: { en: 'intention', nl: 'bedoeling' }, on: 'イ', kun: '' },
  { kanji: '感', grade: 3, meaning: { en: 'feeling', nl: 'gevoel' }, on: 'カン', kun: '' },
  { kanji: '漢', grade: 3, meaning: { en: 'Han Chinese', nl: 'Han-Chinees' }, on: 'カン', kun: '' },
  { kanji: '業', grade: 3, meaning: { en: 'occupation', nl: 'beroep' }, on: 'ギョウ', kun: 'わざ' },
  { kanji: '詩', grade: 3, meaning: { en: 'poem', nl: 'gedicht' }, on: 'シ', kun: '' },
  { kanji: '想', grade: 3, meaning: { en: 'idea', nl: 'idee' }, on: 'ソウ', kun: '' },
  { kanji: '鉄', grade: 3, meaning: { en: 'iron', nl: 'ijzer' }, on: 'テツ', kun: '' },
  { kanji: '農', grade: 3, meaning: { en: 'agriculture', nl: 'landbouw' }, on: 'ノウ', kun: '' },
  { kanji: '福', grade: 3, meaning: { en: 'blessing', nl: 'zegen' }, on: 'フク', kun: '' },
  { kanji: '路', grade: 3, meaning: { en: 'path, route', nl: 'pad, route' }, on: 'ロ', kun: 'じ' },
  { kanji: '歌', grade: 2, meaning: { en: 'song, sing', nl: 'lied, zingen' }, on: 'カ', kun: 'うた' },
  { kanji: '語', grade: 2, meaning: { en: 'language, word', nl: 'taal, woord' }, on: 'ゴ', kun: 'かた.る' },
  { kanji: '算', grade: 2, meaning: { en: 'calculate', nl: 'rekenen' }, on: 'サン', kun: '' },
  { kanji: '読', grade: 2, meaning: { en: 'read', nl: 'lezen' }, on: 'ドク', kun: 'よ.む' },
  { kanji: '聞', grade: 2, meaning: { en: 'hear, listen', nl: 'horen' }, on: 'ブン', kun: 'き.く' },
  { kanji: '鳴', grade: 2, meaning: { en: 'cry, chirp', nl: 'klinken, roepen' }, on: 'メイ', kun: 'な.く' },
  { kanji: '駅', grade: 3, meaning: { en: 'station', nl: 'station' }, on: 'エキ', kun: '' },
  { kanji: '銀', grade: 3, meaning: { en: 'silver', nl: 'zilver' }, on: 'ギン', kun: '' },
  { kanji: '鼻', grade: 3, meaning: { en: 'nose', nl: 'neus' }, on: 'ビ', kun: 'はな' },
  { kanji: '様', grade: 3, meaning: { en: 'manner', nl: 'manier' }, on: 'ヨウ', kun: 'さま' },
  { kanji: '緑', grade: 3, meaning: { en: 'green', nl: 'groen' }, on: 'リョク', kun: 'みどり' },
  { kanji: '練', grade: 3, meaning: { en: 'train, drill', nl: 'trainen, drillen' }, on: 'レン', kun: 'ね.る' },
  { kanji: '線', grade: 2, meaning: { en: 'line', nl: 'lijn' }, on: 'セン', kun: '' },
  { kanji: '横', grade: 3, meaning: { en: 'sideways', nl: 'zijwaarts' }, on: 'オウ', kun: 'よこ' },
  { kanji: '談', grade: 3, meaning: { en: 'discussion', nl: 'gesprek' }, on: 'ダン', kun: '' },
  { kanji: '調', grade: 3, meaning: { en: 'investigate, check', nl: 'nagaan, uitzoeken' }, on: 'チョウ', kun: 'しら.べる' },
  { kanji: '箱', grade: 3, meaning: { en: 'box', nl: 'doos' }, on: '', kun: 'はこ' },
  { kanji: '親', grade: 2, meaning: { en: 'parent', nl: 'ouder' }, on: 'シン', kun: 'おや' },
  { kanji: '頭', grade: 2, meaning: { en: 'head', nl: 'hoofd, kop' }, on: 'トウ', kun: 'あたま' },
  { kanji: '館', grade: 3, meaning: { en: 'hall, building', nl: 'zaal, gebouw' }, on: 'カン', kun: 'やかた' },
  { kanji: '橋', grade: 3, meaning: { en: 'bridge', nl: 'brug' }, on: 'キョウ', kun: 'はし' },
  { kanji: '整', grade: 3, meaning: { en: 'arrange', nl: 'ordenen' }, on: 'セイ', kun: 'ととの.える' },
  { kanji: '薬', grade: 3, meaning: { en: 'medicine', nl: 'medicijn' }, on: 'ヤク', kun: 'くすり' },
  { kanji: '顔', grade: 2, meaning: { en: 'face', nl: 'gezicht' }, on: 'ガン', kun: 'かお' },
  { kanji: '曜', grade: 2, meaning: { en: 'weekday', nl: 'weekdag' }, on: 'ヨウ', kun: '' },
  { kanji: '題', grade: 3, meaning: { en: 'topic', nl: 'onderwerp' }, on: 'ダイ', kun: '' },
];
