/**
 * The deck for the writing proof of concept: the 240 kanji Japanese children
 * learn in their first two years at school.
 *
 * Grades 1 and 2 of the 学年別漢字配当表 (kyoiku kanji) are exactly 80 and 160
 * characters, both in the ministry's own aiueo order.
 *
 * Meanings are kept short on purpose: the prompt has to fit on one line on a
 * phone. They are hand-written per language because no kanji dictionary ships
 * Dutch glosses (KANJIDIC2 has English, French, Spanish and Portuguese only).
 * Readings use the dictionary convention where a dot marks the okurigana
 * boundary.
 */
export const deck = [
  // Grade 1 — 80 kanji
  { kanji: '一', grade: 1, meaning: { en: 'one', nl: 'één' }, on: 'イチ', kun: 'ひと' },
  { kanji: '右', grade: 1, meaning: { en: 'right', nl: 'rechts' }, on: 'ウ', kun: 'みぎ' },
  { kanji: '雨', grade: 1, meaning: { en: 'rain', nl: 'regen' }, on: 'ウ', kun: 'あめ' },
  { kanji: '円', grade: 1, meaning: { en: 'circle, yen', nl: 'cirkel, yen' }, on: 'エン', kun: 'まる' },
  { kanji: '王', grade: 1, meaning: { en: 'king', nl: 'koning' }, on: 'オウ', kun: '' },
  { kanji: '音', grade: 1, meaning: { en: 'sound', nl: 'geluid' }, on: 'オン', kun: 'おと' },
  { kanji: '下', grade: 1, meaning: { en: 'below', nl: 'onder' }, on: 'カ', kun: 'した' },
  { kanji: '火', grade: 1, meaning: { en: 'fire', nl: 'vuur' }, on: 'カ', kun: 'ひ' },
  { kanji: '花', grade: 1, meaning: { en: 'flower', nl: 'bloem' }, on: 'カ', kun: 'はな' },
  { kanji: '貝', grade: 1, meaning: { en: 'shellfish', nl: 'schelp' }, on: '', kun: 'かい' },
  { kanji: '学', grade: 1, meaning: { en: 'study', nl: 'leren' }, on: 'ガク', kun: 'まな.ぶ' },
  { kanji: '気', grade: 1, meaning: { en: 'spirit, air', nl: 'geest, lucht' }, on: 'キ', kun: '' },
  { kanji: '九', grade: 1, meaning: { en: 'nine', nl: 'negen' }, on: 'キュウ', kun: 'ここの' },
  { kanji: '休', grade: 1, meaning: { en: 'rest', nl: 'rusten' }, on: 'キュウ', kun: 'やす.む' },
  { kanji: '玉', grade: 1, meaning: { en: 'jewel, ball', nl: 'edelsteen, bal' }, on: 'ギョク', kun: 'たま' },
  { kanji: '金', grade: 1, meaning: { en: 'gold, money', nl: 'goud, geld' }, on: 'キン', kun: 'かね' },
  { kanji: '空', grade: 1, meaning: { en: 'sky, empty', nl: 'lucht, leeg' }, on: 'クウ', kun: 'そら' },
  { kanji: '月', grade: 1, meaning: { en: 'moon, month', nl: 'maan, maand' }, on: 'ゲツ', kun: 'つき' },
  { kanji: '犬', grade: 1, meaning: { en: 'dog', nl: 'hond' }, on: 'ケン', kun: 'いぬ' },
  { kanji: '見', grade: 1, meaning: { en: 'see', nl: 'zien' }, on: 'ケン', kun: 'み.る' },
  { kanji: '五', grade: 1, meaning: { en: 'five', nl: 'vijf' }, on: 'ゴ', kun: 'いつ' },
  { kanji: '口', grade: 1, meaning: { en: 'mouth', nl: 'mond' }, on: 'コウ', kun: 'くち' },
  { kanji: '校', grade: 1, meaning: { en: 'school', nl: 'school' }, on: 'コウ', kun: '' },
  { kanji: '左', grade: 1, meaning: { en: 'left', nl: 'links' }, on: 'サ', kun: 'ひだり' },
  { kanji: '三', grade: 1, meaning: { en: 'three', nl: 'drie' }, on: 'サン', kun: 'み' },
  { kanji: '山', grade: 1, meaning: { en: 'mountain', nl: 'berg' }, on: 'サン', kun: 'やま' },
  { kanji: '子', grade: 1, meaning: { en: 'child', nl: 'kind' }, on: 'シ', kun: 'こ' },
  { kanji: '四', grade: 1, meaning: { en: 'four', nl: 'vier' }, on: 'シ', kun: 'よ.つ' },
  { kanji: '糸', grade: 1, meaning: { en: 'thread', nl: 'draad' }, on: 'シ', kun: 'いと' },
  { kanji: '字', grade: 1, meaning: { en: 'written character', nl: 'schriftteken' }, on: 'ジ', kun: 'あざ' },
  { kanji: '耳', grade: 1, meaning: { en: 'ear', nl: 'oor' }, on: 'ジ', kun: 'みみ' },
  { kanji: '七', grade: 1, meaning: { en: 'seven', nl: 'zeven' }, on: 'シチ', kun: 'なな' },
  { kanji: '車', grade: 1, meaning: { en: 'car, wheel', nl: 'auto, wiel' }, on: 'シャ', kun: 'くるま' },
  { kanji: '手', grade: 1, meaning: { en: 'hand', nl: 'hand' }, on: 'シュ', kun: 'て' },
  { kanji: '十', grade: 1, meaning: { en: 'ten', nl: 'tien' }, on: 'ジュウ', kun: 'とお' },
  { kanji: '出', grade: 1, meaning: { en: 'exit, go out', nl: 'uitgaan' }, on: 'シュツ', kun: 'で.る' },
  { kanji: '女', grade: 1, meaning: { en: 'woman', nl: 'vrouw' }, on: 'ジョ', kun: 'おんな' },
  { kanji: '小', grade: 1, meaning: { en: 'small', nl: 'klein' }, on: 'ショウ', kun: 'ちい.さい' },
  { kanji: '上', grade: 1, meaning: { en: 'above', nl: 'boven' }, on: 'ジョウ', kun: 'うえ' },
  { kanji: '森', grade: 1, meaning: { en: 'forest', nl: 'woud' }, on: 'シン', kun: 'もり' },
  { kanji: '人', grade: 1, meaning: { en: 'person', nl: 'persoon' }, on: 'ジン', kun: 'ひと' },
  { kanji: '水', grade: 1, meaning: { en: 'water', nl: 'water' }, on: 'スイ', kun: 'みず' },
  { kanji: '正', grade: 1, meaning: { en: 'correct', nl: 'juist' }, on: 'セイ', kun: 'ただ.しい' },
  { kanji: '生', grade: 1, meaning: { en: 'life, birth', nl: 'leven, geboorte' }, on: 'セイ', kun: 'い.きる' },
  { kanji: '青', grade: 1, meaning: { en: 'blue', nl: 'blauw' }, on: 'セイ', kun: 'あお' },
  { kanji: '夕', grade: 1, meaning: { en: 'evening', nl: 'avond' }, on: 'セキ', kun: 'ゆう' },
  { kanji: '石', grade: 1, meaning: { en: 'stone', nl: 'steen' }, on: 'セキ', kun: 'いし' },
  { kanji: '赤', grade: 1, meaning: { en: 'red', nl: 'rood' }, on: 'セキ', kun: 'あか' },
  { kanji: '千', grade: 1, meaning: { en: 'thousand', nl: 'duizend' }, on: 'セン', kun: 'ち' },
  { kanji: '川', grade: 1, meaning: { en: 'river', nl: 'rivier' }, on: 'セン', kun: 'かわ' },
  { kanji: '先', grade: 1, meaning: { en: 'tip, earlier', nl: 'punt, eerder' }, on: 'セン', kun: 'さき' },
  { kanji: '早', grade: 1, meaning: { en: 'early', nl: 'vroeg' }, on: 'ソウ', kun: 'はや.い' },
  { kanji: '草', grade: 1, meaning: { en: 'grass', nl: 'gras' }, on: 'ソウ', kun: 'くさ' },
  { kanji: '足', grade: 1, meaning: { en: 'foot, leg', nl: 'voet, been' }, on: 'ソク', kun: 'あし' },
  { kanji: '村', grade: 1, meaning: { en: 'village', nl: 'dorp' }, on: 'ソン', kun: 'むら' },
  { kanji: '大', grade: 1, meaning: { en: 'big', nl: 'groot' }, on: 'ダイ', kun: 'おお.きい' },
  { kanji: '男', grade: 1, meaning: { en: 'man', nl: 'man' }, on: 'ダン', kun: 'おとこ' },
  { kanji: '竹', grade: 1, meaning: { en: 'bamboo', nl: 'bamboe' }, on: 'チク', kun: 'たけ' },
  { kanji: '中', grade: 1, meaning: { en: 'middle, inside', nl: 'midden, binnen' }, on: 'チュウ', kun: 'なか' },
  { kanji: '虫', grade: 1, meaning: { en: 'insect', nl: 'insect' }, on: 'チュウ', kun: 'むし' },
  { kanji: '町', grade: 1, meaning: { en: 'town', nl: 'stadje' }, on: 'チョウ', kun: 'まち' },
  { kanji: '天', grade: 1, meaning: { en: 'heaven, sky', nl: 'hemel' }, on: 'テン', kun: 'あま' },
  { kanji: '田', grade: 1, meaning: { en: 'rice field', nl: 'rijstveld' }, on: 'デン', kun: 'た' },
  { kanji: '土', grade: 1, meaning: { en: 'earth, soil', nl: 'aarde, grond' }, on: 'ド', kun: 'つち' },
  { kanji: '二', grade: 1, meaning: { en: 'two', nl: 'twee' }, on: 'ニ', kun: 'ふた' },
  { kanji: '日', grade: 1, meaning: { en: 'day, sun', nl: 'dag, zon' }, on: 'ニチ', kun: 'ひ' },
  { kanji: '入', grade: 1, meaning: { en: 'enter', nl: 'binnengaan' }, on: 'ニュウ', kun: 'はい.る' },
  { kanji: '年', grade: 1, meaning: { en: 'year', nl: 'jaar' }, on: 'ネン', kun: 'とし' },
  { kanji: '白', grade: 1, meaning: { en: 'white', nl: 'wit' }, on: 'ハク', kun: 'しろ.い' },
  { kanji: '八', grade: 1, meaning: { en: 'eight', nl: 'acht' }, on: 'ハチ', kun: 'や.つ' },
  { kanji: '百', grade: 1, meaning: { en: 'hundred', nl: 'honderd' }, on: 'ヒャク', kun: '' },
  { kanji: '文', grade: 1, meaning: { en: 'writing, sentence', nl: 'tekst, zin' }, on: 'ブン', kun: 'ふみ' },
  { kanji: '木', grade: 1, meaning: { en: 'tree, wood', nl: 'boom, hout' }, on: 'モク', kun: 'き' },
  { kanji: '本', grade: 1, meaning: { en: 'book, origin', nl: 'boek, oorsprong' }, on: 'ホン', kun: 'もと' },
  { kanji: '名', grade: 1, meaning: { en: 'name', nl: 'naam' }, on: 'メイ', kun: 'な' },
  { kanji: '目', grade: 1, meaning: { en: 'eye', nl: 'oog' }, on: 'モク', kun: 'め' },
  { kanji: '立', grade: 1, meaning: { en: 'stand up', nl: 'staan, opstaan' }, on: 'リツ', kun: 'た.つ' },
  { kanji: '力', grade: 1, meaning: { en: 'power', nl: 'kracht' }, on: 'リョク', kun: 'ちから' },
  { kanji: '林', grade: 1, meaning: { en: 'woods', nl: 'bos' }, on: 'リン', kun: 'はやし' },
  { kanji: '六', grade: 1, meaning: { en: 'six', nl: 'zes' }, on: 'ロク', kun: 'む.つ' },

  // Grade 2 — all 160, in the same order
  { kanji: '引', grade: 2, meaning: { en: 'pull', nl: 'trekken' }, on: 'イン', kun: 'ひ.く' },
  { kanji: '羽', grade: 2, meaning: { en: 'feather, wing', nl: 'veer, vleugel' }, on: 'ウ', kun: 'はね' },
  { kanji: '雲', grade: 2, meaning: { en: 'cloud', nl: 'wolk' }, on: 'ウン', kun: 'くも' },
  { kanji: '園', grade: 2, meaning: { en: 'garden, park', nl: 'tuin, park' }, on: 'エン', kun: 'その' },
  { kanji: '遠', grade: 2, meaning: { en: 'far', nl: 'ver' }, on: 'エン', kun: 'とお.い' },
  { kanji: '何', grade: 2, meaning: { en: 'what', nl: 'wat' }, on: 'カ', kun: 'なに' },
  { kanji: '科', grade: 2, meaning: { en: 'course, section', nl: 'vak, afdeling' }, on: 'カ', kun: '' },
  { kanji: '夏', grade: 2, meaning: { en: 'summer', nl: 'zomer' }, on: 'カ', kun: 'なつ' },
  { kanji: '家', grade: 2, meaning: { en: 'house, family', nl: 'huis, gezin' }, on: 'カ', kun: 'いえ' },
  { kanji: '歌', grade: 2, meaning: { en: 'song, sing', nl: 'lied, zingen' }, on: 'カ', kun: 'うた' },
  { kanji: '画', grade: 2, meaning: { en: 'image, stroke', nl: 'beeld, streek' }, on: 'ガ', kun: '' },
  { kanji: '回', grade: 2, meaning: { en: 'times, revolve', nl: 'keer, draaien' }, on: 'カイ', kun: 'まわ.る' },
  { kanji: '会', grade: 2, meaning: { en: 'meet', nl: 'ontmoeten' }, on: 'カイ', kun: 'あ.う' },
  { kanji: '海', grade: 2, meaning: { en: 'sea', nl: 'zee' }, on: 'カイ', kun: 'うみ' },
  { kanji: '絵', grade: 2, meaning: { en: 'drawing', nl: 'tekening' }, on: 'カイ', kun: 'え' },
  { kanji: '外', grade: 2, meaning: { en: 'outside', nl: 'buiten' }, on: 'ガイ', kun: 'そと' },
  { kanji: '角', grade: 2, meaning: { en: 'corner, horn', nl: 'hoek, hoorn' }, on: 'カク', kun: 'かど' },
  { kanji: '楽', grade: 2, meaning: { en: 'fun, music', nl: 'plezier, muziek' }, on: 'ガク', kun: 'たの.しい' },
  { kanji: '活', grade: 2, meaning: { en: 'lively, activity', nl: 'activiteit' }, on: 'カツ', kun: '' },
  { kanji: '間', grade: 2, meaning: { en: 'interval, between', nl: 'tussen, interval' }, on: 'カン', kun: 'あいだ' },
  { kanji: '丸', grade: 2, meaning: { en: 'round', nl: 'rond' }, on: 'ガン', kun: 'まる' },
  { kanji: '岩', grade: 2, meaning: { en: 'rock', nl: 'rots' }, on: 'ガン', kun: 'いわ' },
  { kanji: '顔', grade: 2, meaning: { en: 'face', nl: 'gezicht' }, on: 'ガン', kun: 'かお' },
  { kanji: '汽', grade: 2, meaning: { en: 'steam', nl: 'stoom' }, on: 'キ', kun: '' },
  { kanji: '記', grade: 2, meaning: { en: 'record, write down', nl: 'opschrijven' }, on: 'キ', kun: 'しる.す' },
  { kanji: '帰', grade: 2, meaning: { en: 'return home', nl: 'terugkeren' }, on: 'キ', kun: 'かえ.る' },
  { kanji: '弓', grade: 2, meaning: { en: 'bow', nl: 'boog' }, on: 'キュウ', kun: 'ゆみ' },
  { kanji: '牛', grade: 2, meaning: { en: 'cow', nl: 'koe' }, on: 'ギュウ', kun: 'うし' },
  { kanji: '魚', grade: 2, meaning: { en: 'fish', nl: 'vis' }, on: 'ギョ', kun: 'さかな' },
  { kanji: '京', grade: 2, meaning: { en: 'capital', nl: 'hoofdstad' }, on: 'キョウ', kun: '' },
  { kanji: '強', grade: 2, meaning: { en: 'strong', nl: 'sterk' }, on: 'キョウ', kun: 'つよ.い' },
  { kanji: '教', grade: 2, meaning: { en: 'teach', nl: 'onderwijzen' }, on: 'キョウ', kun: 'おし.える' },
  { kanji: '近', grade: 2, meaning: { en: 'near', nl: 'dichtbij' }, on: 'キン', kun: 'ちか.い' },
  { kanji: '兄', grade: 2, meaning: { en: 'older brother', nl: 'oudere broer' }, on: 'ケイ', kun: 'あに' },
  { kanji: '形', grade: 2, meaning: { en: 'shape', nl: 'vorm' }, on: 'ケイ', kun: 'かたち' },
  { kanji: '計', grade: 2, meaning: { en: 'measure, plan', nl: 'meten, plan' }, on: 'ケイ', kun: 'はか.る' },
  { kanji: '元', grade: 2, meaning: { en: 'origin', nl: 'oorsprong' }, on: 'ゲン', kun: 'もと' },
  { kanji: '言', grade: 2, meaning: { en: 'say', nl: 'zeggen' }, on: 'ゲン', kun: 'い.う' },
  { kanji: '原', grade: 2, meaning: { en: 'plain, field', nl: 'vlakte' }, on: 'ゲン', kun: 'はら' },
  { kanji: '戸', grade: 2, meaning: { en: 'door', nl: 'deur' }, on: 'コ', kun: 'と' },
  { kanji: '古', grade: 2, meaning: { en: 'old', nl: 'oud' }, on: 'コ', kun: 'ふる.い' },
  { kanji: '午', grade: 2, meaning: { en: 'midday hour', nl: 'twaalf uur' }, on: 'ゴ', kun: '' },
  { kanji: '後', grade: 2, meaning: { en: 'after, behind', nl: 'na, achter' }, on: 'ゴ', kun: 'あと' },
  { kanji: '語', grade: 2, meaning: { en: 'language, word', nl: 'taal, woord' }, on: 'ゴ', kun: 'かた.る' },
  { kanji: '工', grade: 2, meaning: { en: 'craft, works', nl: 'ambacht' }, on: 'コウ', kun: '' },
  { kanji: '公', grade: 2, meaning: { en: 'public', nl: 'openbaar' }, on: 'コウ', kun: '' },
  { kanji: '広', grade: 2, meaning: { en: 'wide', nl: 'breed' }, on: 'コウ', kun: 'ひろ.い' },
  { kanji: '交', grade: 2, meaning: { en: 'cross, exchange', nl: 'kruisen' }, on: 'コウ', kun: 'まじ.わる' },
  { kanji: '光', grade: 2, meaning: { en: 'light, shine', nl: 'licht' }, on: 'コウ', kun: 'ひかり' },
  { kanji: '考', grade: 2, meaning: { en: 'consider', nl: 'nadenken' }, on: 'コウ', kun: 'かんが.える' },
  { kanji: '行', grade: 2, meaning: { en: 'go', nl: 'gaan' }, on: 'コウ', kun: 'い.く' },
  { kanji: '高', grade: 2, meaning: { en: 'high, tall', nl: 'hoog' }, on: 'コウ', kun: 'たか.い' },
  { kanji: '黄', grade: 2, meaning: { en: 'yellow', nl: 'geel' }, on: 'コウ', kun: 'き' },
  { kanji: '合', grade: 2, meaning: { en: 'fit, join', nl: 'passen, samen' }, on: 'ゴウ', kun: 'あ.う' },
  { kanji: '谷', grade: 2, meaning: { en: 'valley', nl: 'vallei' }, on: 'コク', kun: 'たに' },
  { kanji: '国', grade: 2, meaning: { en: 'country', nl: 'land' }, on: 'コク', kun: 'くに' },
  { kanji: '黒', grade: 2, meaning: { en: 'black', nl: 'zwart' }, on: 'コク', kun: 'くろ' },
  { kanji: '今', grade: 2, meaning: { en: 'now', nl: 'nu' }, on: 'コン', kun: 'いま' },
  { kanji: '才', grade: 2, meaning: { en: 'talent', nl: 'talent' }, on: 'サイ', kun: '' },
  { kanji: '細', grade: 2, meaning: { en: 'thin, fine', nl: 'dun, fijn' }, on: 'サイ', kun: 'ほそ.い' },
  { kanji: '作', grade: 2, meaning: { en: 'make', nl: 'maken' }, on: 'サク', kun: 'つく.る' },
  { kanji: '算', grade: 2, meaning: { en: 'calculate', nl: 'rekenen' }, on: 'サン', kun: '' },
  { kanji: '止', grade: 2, meaning: { en: 'stop', nl: 'stoppen' }, on: 'シ', kun: 'と.まる' },
  { kanji: '市', grade: 2, meaning: { en: 'city, market', nl: 'stad, markt' }, on: 'シ', kun: 'いち' },
  { kanji: '矢', grade: 2, meaning: { en: 'arrow', nl: 'pijl' }, on: 'シ', kun: 'や' },
  { kanji: '姉', grade: 2, meaning: { en: 'older sister', nl: 'oudere zus' }, on: 'シ', kun: 'あね' },
  { kanji: '思', grade: 2, meaning: { en: 'think, feel', nl: 'denken, vinden' }, on: 'シ', kun: 'おも.う' },
  { kanji: '紙', grade: 2, meaning: { en: 'paper', nl: 'papier' }, on: 'シ', kun: 'かみ' },
  { kanji: '寺', grade: 2, meaning: { en: 'temple', nl: 'tempel' }, on: 'ジ', kun: 'てら' },
  { kanji: '自', grade: 2, meaning: { en: 'self, own', nl: 'zelf, eigen' }, on: 'ジ', kun: 'みずか.ら' },
  { kanji: '時', grade: 2, meaning: { en: 'time, hour', nl: 'tijd, uur' }, on: 'ジ', kun: 'とき' },
  { kanji: '室', grade: 2, meaning: { en: 'room', nl: 'kamer' }, on: 'シツ', kun: 'むろ' },
  { kanji: '社', grade: 2, meaning: { en: 'company, shrine', nl: 'bedrijf, heiligdom' }, on: 'シャ', kun: 'やしろ' },
  { kanji: '弱', grade: 2, meaning: { en: 'weak', nl: 'zwak' }, on: 'ジャク', kun: 'よわ.い' },
  { kanji: '首', grade: 2, meaning: { en: 'neck', nl: 'nek' }, on: 'シュ', kun: 'くび' },
  { kanji: '秋', grade: 2, meaning: { en: 'autumn', nl: 'herfst' }, on: 'シュウ', kun: 'あき' },
  { kanji: '週', grade: 2, meaning: { en: 'week', nl: 'week' }, on: 'シュウ', kun: '' },
  { kanji: '春', grade: 2, meaning: { en: 'spring', nl: 'lente' }, on: 'シュン', kun: 'はる' },
  { kanji: '書', grade: 2, meaning: { en: 'write', nl: 'schrijven' }, on: 'ショ', kun: 'か.く' },
  { kanji: '少', grade: 2, meaning: { en: 'few, little', nl: 'weinig' }, on: 'ショウ', kun: 'すこ.し' },
  { kanji: '場', grade: 2, meaning: { en: 'place', nl: 'plaats' }, on: 'ジョウ', kun: 'ば' },
  { kanji: '色', grade: 2, meaning: { en: 'colour', nl: 'kleur' }, on: 'ショク', kun: 'いろ' },
  { kanji: '食', grade: 2, meaning: { en: 'eat, food', nl: 'eten' }, on: 'ショク', kun: 'た.べる' },
  { kanji: '心', grade: 2, meaning: { en: 'heart', nl: 'hart' }, on: 'シン', kun: 'こころ' },
  { kanji: '新', grade: 2, meaning: { en: 'new', nl: 'nieuw' }, on: 'シン', kun: 'あたら.しい' },
  { kanji: '親', grade: 2, meaning: { en: 'parent', nl: 'ouder' }, on: 'シン', kun: 'おや' },
  { kanji: '図', grade: 2, meaning: { en: 'diagram, map', nl: 'schema, kaart' }, on: 'ズ', kun: 'はか.る' },
  { kanji: '数', grade: 2, meaning: { en: 'number, count', nl: 'aantal, tellen' }, on: 'スウ', kun: 'かず' },
  { kanji: '西', grade: 2, meaning: { en: 'west', nl: 'west' }, on: 'セイ', kun: 'にし' },
  { kanji: '声', grade: 2, meaning: { en: 'voice', nl: 'stem' }, on: 'セイ', kun: 'こえ' },
  { kanji: '星', grade: 2, meaning: { en: 'star', nl: 'ster' }, on: 'セイ', kun: 'ほし' },
  { kanji: '晴', grade: 2, meaning: { en: 'clear up', nl: 'opklaren' }, on: 'セイ', kun: 'は.れる' },
  { kanji: '切', grade: 2, meaning: { en: 'cut', nl: 'snijden' }, on: 'セツ', kun: 'き.る' },
  { kanji: '雪', grade: 2, meaning: { en: 'snow', nl: 'sneeuw' }, on: 'セツ', kun: 'ゆき' },
  { kanji: '船', grade: 2, meaning: { en: 'ship', nl: 'schip' }, on: 'セン', kun: 'ふね' },
  { kanji: '線', grade: 2, meaning: { en: 'line', nl: 'lijn' }, on: 'セン', kun: '' },
  { kanji: '前', grade: 2, meaning: { en: 'front, before', nl: 'voor, voorkant' }, on: 'ゼン', kun: 'まえ' },
  { kanji: '組', grade: 2, meaning: { en: 'group, assemble', nl: 'groep, samenstellen' }, on: 'ソ', kun: 'く.む' },
  { kanji: '走', grade: 2, meaning: { en: 'run', nl: 'rennen' }, on: 'ソウ', kun: 'はし.る' },
  { kanji: '多', grade: 2, meaning: { en: 'many', nl: 'veel' }, on: 'タ', kun: 'おお.い' },
  { kanji: '太', grade: 2, meaning: { en: 'thick, fat', nl: 'dik' }, on: 'タイ', kun: 'ふと.い' },
  { kanji: '体', grade: 2, meaning: { en: 'body', nl: 'lichaam' }, on: 'タイ', kun: 'からだ' },
  { kanji: '台', grade: 2, meaning: { en: 'platform', nl: 'standaard' }, on: 'ダイ', kun: '' },
  { kanji: '地', grade: 2, meaning: { en: 'ground, land', nl: 'grond, land' }, on: 'チ', kun: '' },
  { kanji: '池', grade: 2, meaning: { en: 'pond', nl: 'vijver' }, on: 'チ', kun: 'いけ' },
  { kanji: '知', grade: 2, meaning: { en: 'know', nl: 'weten' }, on: 'チ', kun: 'し.る' },
  { kanji: '茶', grade: 2, meaning: { en: 'tea', nl: 'thee' }, on: 'チャ', kun: '' },
  { kanji: '昼', grade: 2, meaning: { en: 'daytime', nl: 'middag, overdag' }, on: 'チュウ', kun: 'ひる' },
  { kanji: '長', grade: 2, meaning: { en: 'long, chief', nl: 'lang, hoofd' }, on: 'チョウ', kun: 'なが.い' },
  { kanji: '鳥', grade: 2, meaning: { en: 'bird', nl: 'vogel' }, on: 'チョウ', kun: 'とり' },
  { kanji: '朝', grade: 2, meaning: { en: 'morning', nl: 'ochtend' }, on: 'チョウ', kun: 'あさ' },
  { kanji: '直', grade: 2, meaning: { en: 'straight, fix', nl: 'recht, herstellen' }, on: 'チョク', kun: 'なお.す' },
  { kanji: '通', grade: 2, meaning: { en: 'pass through', nl: 'doorgaan' }, on: 'ツウ', kun: 'とお.る' },
  { kanji: '弟', grade: 2, meaning: { en: 'younger brother', nl: 'jongere broer' }, on: 'テイ', kun: 'おとうと' },
  { kanji: '店', grade: 2, meaning: { en: 'shop', nl: 'winkel' }, on: 'テン', kun: 'みせ' },
  { kanji: '点', grade: 2, meaning: { en: 'point, dot', nl: 'punt' }, on: 'テン', kun: '' },
  { kanji: '電', grade: 2, meaning: { en: 'electricity', nl: 'elektriciteit' }, on: 'デン', kun: '' },
  { kanji: '刀', grade: 2, meaning: { en: 'sword', nl: 'zwaard' }, on: 'トウ', kun: 'かたな' },
  { kanji: '冬', grade: 2, meaning: { en: 'winter', nl: 'winter' }, on: 'トウ', kun: 'ふゆ' },
  { kanji: '当', grade: 2, meaning: { en: 'hit, this', nl: 'raken, deze' }, on: 'トウ', kun: 'あ.たる' },
  { kanji: '東', grade: 2, meaning: { en: 'east', nl: 'oost' }, on: 'トウ', kun: 'ひがし' },
  { kanji: '答', grade: 2, meaning: { en: 'answer', nl: 'antwoord' }, on: 'トウ', kun: 'こた.える' },
  { kanji: '頭', grade: 2, meaning: { en: 'head', nl: 'hoofd, kop' }, on: 'トウ', kun: 'あたま' },
  { kanji: '同', grade: 2, meaning: { en: 'same', nl: 'hetzelfde' }, on: 'ドウ', kun: 'おな.じ' },
  { kanji: '道', grade: 2, meaning: { en: 'road, way', nl: 'weg' }, on: 'ドウ', kun: 'みち' },
  { kanji: '読', grade: 2, meaning: { en: 'read', nl: 'lezen' }, on: 'ドク', kun: 'よ.む' },
  { kanji: '内', grade: 2, meaning: { en: 'inside', nl: 'binnenkant' }, on: 'ナイ', kun: 'うち' },
  { kanji: '南', grade: 2, meaning: { en: 'south', nl: 'zuid' }, on: 'ナン', kun: 'みなみ' },
  { kanji: '肉', grade: 2, meaning: { en: 'meat', nl: 'vlees' }, on: 'ニク', kun: '' },
  { kanji: '馬', grade: 2, meaning: { en: 'horse', nl: 'paard' }, on: 'バ', kun: 'うま' },
  { kanji: '売', grade: 2, meaning: { en: 'sell', nl: 'verkopen' }, on: 'バイ', kun: 'う.る' },
  { kanji: '買', grade: 2, meaning: { en: 'buy', nl: 'kopen' }, on: 'バイ', kun: 'か.う' },
  { kanji: '麦', grade: 2, meaning: { en: 'wheat', nl: 'tarwe' }, on: 'バク', kun: 'むぎ' },
  { kanji: '半', grade: 2, meaning: { en: 'half', nl: 'half' }, on: 'ハン', kun: 'なか.ば' },
  { kanji: '番', grade: 2, meaning: { en: 'number in order', nl: 'beurt, nummer' }, on: 'バン', kun: '' },
  { kanji: '父', grade: 2, meaning: { en: 'father', nl: 'vader' }, on: 'フ', kun: 'ちち' },
  { kanji: '風', grade: 2, meaning: { en: 'wind', nl: 'wind' }, on: 'フウ', kun: 'かぜ' },
  { kanji: '分', grade: 2, meaning: { en: 'divide, minute', nl: 'verdelen, minuut' }, on: 'ブン', kun: 'わ.ける' },
  { kanji: '聞', grade: 2, meaning: { en: 'hear, listen', nl: 'horen' }, on: 'ブン', kun: 'き.く' },
  { kanji: '米', grade: 2, meaning: { en: 'rice', nl: 'rijst' }, on: 'ベイ', kun: 'こめ' },
  { kanji: '歩', grade: 2, meaning: { en: 'walk', nl: 'lopen' }, on: 'ホ', kun: 'ある.く' },
  { kanji: '母', grade: 2, meaning: { en: 'mother', nl: 'moeder' }, on: 'ボ', kun: 'はは' },
  { kanji: '方', grade: 2, meaning: { en: 'direction, way', nl: 'richting' }, on: 'ホウ', kun: 'かた' },
  { kanji: '北', grade: 2, meaning: { en: 'north', nl: 'noord' }, on: 'ホク', kun: 'きた' },
  { kanji: '毎', grade: 2, meaning: { en: 'every', nl: 'elke' }, on: 'マイ', kun: '' },
  { kanji: '妹', grade: 2, meaning: { en: 'younger sister', nl: 'jongere zus' }, on: 'マイ', kun: 'いもうと' },
  { kanji: '万', grade: 2, meaning: { en: 'ten thousand', nl: 'tienduizend' }, on: 'マン', kun: '' },
  { kanji: '明', grade: 2, meaning: { en: 'bright, clear', nl: 'helder' }, on: 'メイ', kun: 'あか.るい' },
  { kanji: '鳴', grade: 2, meaning: { en: 'cry, chirp', nl: 'klinken, roepen' }, on: 'メイ', kun: 'な.く' },
  { kanji: '毛', grade: 2, meaning: { en: 'hair, fur', nl: 'haar, vacht' }, on: 'モウ', kun: 'け' },
  { kanji: '門', grade: 2, meaning: { en: 'gate', nl: 'poort' }, on: 'モン', kun: 'かど' },
  { kanji: '夜', grade: 2, meaning: { en: 'night', nl: 'nacht' }, on: 'ヤ', kun: 'よる' },
  { kanji: '野', grade: 2, meaning: { en: 'field', nl: 'veld' }, on: 'ヤ', kun: 'の' },
  { kanji: '友', grade: 2, meaning: { en: 'friend', nl: 'vriend' }, on: 'ユウ', kun: 'とも' },
  { kanji: '用', grade: 2, meaning: { en: 'use', nl: 'gebruiken' }, on: 'ヨウ', kun: 'もち.いる' },
  { kanji: '曜', grade: 2, meaning: { en: 'weekday', nl: 'weekdag' }, on: 'ヨウ', kun: '' },
  { kanji: '来', grade: 2, meaning: { en: 'come', nl: 'komen' }, on: 'ライ', kun: 'く.る' },
  { kanji: '里', grade: 2, meaning: { en: 'hometown', nl: 'geboortestreek' }, on: 'リ', kun: 'さと' },
  { kanji: '理', grade: 2, meaning: { en: 'reason, logic', nl: 'rede, logica' }, on: 'リ', kun: '' },
  { kanji: '話', grade: 2, meaning: { en: 'talk, story', nl: 'praten, verhaal' }, on: 'ワ', kun: 'はな.す' },
];
