/**
 * The deck for the writing proof of concept: the 642 kanji Japanese children
 * learn in their first four years at school.
 *
 * Grades 1 to 4 of the 学年別漢字配当表 (kyoiku kanji), exactly 80, 160, 200
 * and 202 characters - the grade 4 of the 2020 revision, prefecture kanji and
 * all. They are listed in learning order, not the ministry's aiueo
 * order. The order is a cascade: every kanji comes after the deck kanji it is
 * built from (per KanjiVG's decomposition), the school grades run in order
 * below that rule, and within a grade the more common kanji come first -
 * except the first grade, which takes the simplest strokes first while the
 * hand is still being built. A part is pulled in right before the earliest
 * kanji that needs it, whatever the grades say - 化 (grade 3) arrives just
 * before 花 (grade 1) - so lessons follow this list top to bottom. The order
 * is computed by sort-deck.mjs, and stroke-data.spec.ts rejects a kanji
 * placed above its parts.
 *
 * Meanings are short where a short word will do, but being understood comes
 * first: a review has room for a phrase, and the practice list cuts off with
 * an ellipsis what will not fit under a tile. They are hand-written per
 * language because no kanji dictionary ships Dutch glosses (KANJIDIC2 has
 * English, French, Spanish and Portuguese only). Readings use the dictionary
 * convention where a dot marks the okurigana boundary.
 *
 * A meaning is the whole question in a review, so when adding kanji:
 *
 * - Pick words that mean one thing on their own. 台 was "standaard", which is
 *   both a stand and a default; it is now "platform, standaard", where the
 *   two senses pin each other down.
 * - Two plain words beat one odd word chosen to dodge a clash, and both
 *   languages get the pair, so they ask the same question: 練 is "train,
 *   drill" and "trainen, drillen", because "train" alone is a locomotive.
 * - Never let two kanji claim the same word, in either language. Write the
 *   sense that separates them instead - 森 is a "woud", 林 a "bos".
 * - A word in brackets names the sense meant, and is the one way two kanji may
 *   share a word: 軽 is "licht (gewicht)" where 光 is "licht (schijnsel)". Use
 *   it wherever the bare word leaves the question open - "koud (weer)" is not
 *   the cold of a cold hand.
 *
 * stroke-data.spec.ts enforces those last two on the generated file.
 */
export const deck = [
  { kanji: '一', grade: 1, meaning: { en: 'one', nl: 'één' }, on: 'イチ', kun: 'ひと' },
  { kanji: '人', grade: 1, meaning: { en: 'person', nl: 'persoon' }, on: 'ジン', kun: 'ひと' },
  { kanji: '入', grade: 1, meaning: { en: 'enter', nl: 'binnengaan' }, on: 'ニュウ', kun: 'はい.る' },
  { kanji: '二', grade: 1, meaning: { en: 'two', nl: 'twee' }, on: 'ニ', kun: 'ふた' },
  { kanji: '力', grade: 1, meaning: { en: 'power', nl: 'kracht' }, on: 'リョク', kun: 'ちから' },
  { kanji: '十', grade: 1, meaning: { en: 'ten', nl: 'tien' }, on: 'ジュウ', kun: 'とお' },
  { kanji: '八', grade: 1, meaning: { en: 'eight', nl: 'acht' }, on: 'ハチ', kun: 'や.つ' },
  { kanji: '九', grade: 1, meaning: { en: 'nine', nl: 'negen' }, on: 'キュウ', kun: 'ここの' },
  { kanji: '七', grade: 1, meaning: { en: 'seven', nl: 'zeven' }, on: 'シチ', kun: 'なな' },
  { kanji: '大', grade: 1, meaning: { en: 'big', nl: 'groot' }, on: 'ダイ', kun: 'おお.きい' },
  { kanji: '上', grade: 1, meaning: { en: 'above', nl: 'boven' }, on: 'ジョウ', kun: 'うえ' },
  { kanji: '子', grade: 1, meaning: { en: 'child', nl: 'kind' }, on: 'シ', kun: 'こ' },
  { kanji: '山', grade: 1, meaning: { en: 'mountain', nl: 'berg' }, on: 'サン', kun: 'やま' },
  { kanji: '下', grade: 1, meaning: { en: 'below', nl: 'onder' }, on: 'カ', kun: 'した' },
  { kanji: '女', grade: 1, meaning: { en: 'woman', nl: 'vrouw' }, on: 'ジョ', kun: 'おんな' },
  { kanji: '小', grade: 1, meaning: { en: 'small', nl: 'klein' }, on: 'ショウ', kun: 'ちい.さい' },
  { kanji: '三', grade: 1, meaning: { en: 'three', nl: 'drie' }, on: 'サン', kun: 'み' },
  { kanji: '川', grade: 1, meaning: { en: 'river', nl: 'rivier' }, on: 'セン', kun: 'かわ' },
  { kanji: '口', grade: 1, meaning: { en: 'mouth', nl: 'mond' }, on: 'コウ', kun: 'くち' },
  { kanji: '土', grade: 1, meaning: { en: 'earth, soil', nl: 'aarde, grond' }, on: 'ド', kun: 'つち' },
  { kanji: '千', grade: 1, meaning: { en: 'thousand', nl: 'duizend' }, on: 'セン', kun: 'ち' },
  { kanji: '夕', grade: 1, meaning: { en: 'evening', nl: 'avond' }, on: 'セキ', kun: 'ゆう' },
  { kanji: '日', grade: 1, meaning: { en: 'day, sun', nl: 'dag, zon' }, on: 'ニチ', kun: 'ひ' },
  { kanji: '月', grade: 1, meaning: { en: 'moon, month', nl: 'maan, maand' }, on: 'ゲツ', kun: 'つき' },
  { kanji: '中', grade: 1, meaning: { en: 'middle, centre', nl: 'midden, centrum' }, on: 'チュウ', kun: 'なか' },
  { kanji: '手', grade: 1, meaning: { en: 'hand', nl: 'hand' }, on: 'シュ', kun: 'て' },
  { kanji: '文', grade: 1, meaning: { en: 'writing, sentence', nl: 'tekst, zin' }, on: 'ブン', kun: 'ふみ' },
  { kanji: '水', grade: 1, meaning: { en: 'water', nl: 'water' }, on: 'スイ', kun: 'みず' },
  { kanji: '木', grade: 1, meaning: { en: 'tree, wood', nl: 'boom, hout' }, on: 'モク', kun: 'き' },
  { kanji: '天', grade: 1, meaning: { en: 'heaven', nl: 'hemel' }, on: 'テン', kun: 'あま' },
  { kanji: '王', grade: 1, meaning: { en: 'king', nl: 'koning' }, on: 'オウ', kun: '' },
  { kanji: '五', grade: 1, meaning: { en: 'five', nl: 'vijf' }, on: 'ゴ', kun: 'いつ' },
  { kanji: '火', grade: 1, meaning: { en: 'fire', nl: 'vuur' }, on: 'カ', kun: 'ひ' },
  { kanji: '円', grade: 1, meaning: { en: 'circle, yen', nl: 'cirkel, yen' }, on: 'エン', kun: 'まる' },
  { kanji: '六', grade: 1, meaning: { en: 'six', nl: 'zes' }, on: 'ロク', kun: 'む.つ' },
  { kanji: '犬', grade: 1, meaning: { en: 'dog', nl: 'hond' }, on: 'ケン', kun: 'いぬ' },
  { kanji: '本', grade: 1, meaning: { en: 'book, origin', nl: 'boek, oorsprong' }, on: 'ホン', kun: 'もと' },
  { kanji: '出', grade: 1, meaning: { en: 'exit, leave', nl: 'uitgaan' }, on: 'シュツ', kun: 'で.る' },
  { kanji: '生', grade: 1, meaning: { en: 'life, birth', nl: 'leven, geboorte' }, on: 'セイ', kun: 'い.きる' },
  { kanji: '田', grade: 1, meaning: { en: 'paddy', nl: 'rijstveld' }, on: 'デン', kun: 'た' },
  { kanji: '立', grade: 1, meaning: { en: 'stand up', nl: 'staan, opstaan' }, on: 'リツ', kun: 'た.つ' },
  { kanji: '目', grade: 1, meaning: { en: 'eye', nl: 'oog' }, on: 'モク', kun: 'め' },
  { kanji: '止', grade: 2, meaning: { en: 'stop', nl: 'stoppen' }, on: 'シ', kun: 'と.まる' },
  { kanji: '正', grade: 1, meaning: { en: 'correct', nl: 'juist' }, on: 'セイ', kun: 'ただ.しい' },
  { kanji: '石', grade: 1, meaning: { en: 'stone', nl: 'steen' }, on: 'セキ', kun: 'いし' },
  { kanji: '白', grade: 1, meaning: { en: 'white', nl: 'wit' }, on: 'ハク', kun: 'しろ.い' },
  { kanji: '四', grade: 1, meaning: { en: 'four', nl: 'vier' }, on: 'シ', kun: 'よ.つ' },
  { kanji: '工', grade: 2, meaning: { en: 'craft, works', nl: 'ambacht' }, on: 'コウ', kun: '' },
  { kanji: '左', grade: 1, meaning: { en: 'left', nl: 'links' }, on: 'サ', kun: 'ひだり' },
  { kanji: '右', grade: 1, meaning: { en: 'right', nl: 'rechts' }, on: 'ウ', kun: 'みぎ' },
  { kanji: '玉', grade: 1, meaning: { en: 'jewel, ball', nl: 'edelsteen, bal' }, on: 'ギョク', kun: 'たま' },
  { kanji: '年', grade: 1, meaning: { en: 'year', nl: 'jaar' }, on: 'ネン', kun: 'とし' },
  { kanji: '名', grade: 1, meaning: { en: 'name', nl: 'naam' }, on: 'メイ', kun: 'な' },
  { kanji: '気', grade: 1, meaning: { en: 'spirit, air', nl: 'geest, stemming' }, on: 'キ', kun: '' },
  { kanji: '先', grade: 1, meaning: { en: 'tip, earlier', nl: 'vorig, vooruit' }, on: 'セン', kun: 'さき' },
  { kanji: '字', grade: 1, meaning: { en: 'written character', nl: 'schriftteken' }, on: 'ジ', kun: 'あざ' },
  { kanji: '早', grade: 1, meaning: { en: 'early', nl: 'vroeg' }, on: 'ソウ', kun: 'はや.い' },
  { kanji: '百', grade: 1, meaning: { en: 'hundred', nl: 'honderd' }, on: 'ヒャク', kun: '' },
  { kanji: '休', grade: 1, meaning: { en: 'rest', nl: 'rusten' }, on: 'キュウ', kun: 'やす.む' },
  { kanji: '竹', grade: 1, meaning: { en: 'bamboo', nl: 'bamboe' }, on: 'チク', kun: 'たけ' },
  { kanji: '耳', grade: 1, meaning: { en: 'ear', nl: 'oor' }, on: 'ジ', kun: 'みみ' },
  { kanji: '虫', grade: 1, meaning: { en: 'insect', nl: 'insect' }, on: 'チュウ', kun: 'むし' },
  { kanji: '糸', grade: 1, meaning: { en: 'thread', nl: 'draad' }, on: 'シ', kun: 'いと' },
  { kanji: '見', grade: 1, meaning: { en: 'see', nl: 'zien' }, on: 'ケン', kun: 'み.る' },
  { kanji: '車', grade: 1, meaning: { en: 'car, wheel', nl: 'auto, wiel' }, on: 'シャ', kun: 'くるま' },
  { kanji: '丁', grade: 3, meaning: { en: 'street block', nl: 'huizenblok' }, on: 'チョウ', kun: '' },
  { kanji: '町', grade: 1, meaning: { en: 'town', nl: 'stadje' }, on: 'チョウ', kun: 'まち' },
  { kanji: '村', grade: 1, meaning: { en: 'village', nl: 'dorp' }, on: 'ソン', kun: 'むら' },
  { kanji: '男', grade: 1, meaning: { en: 'man', nl: 'man' }, on: 'ダン', kun: 'おとこ' },
  { kanji: '足', grade: 1, meaning: { en: 'foot, leg', nl: 'voet, been' }, on: 'ソク', kun: 'あし' },
  { kanji: '化', grade: 3, meaning: { en: 'transform', nl: 'omvormen, veranderen' }, on: 'カ', kun: 'ば.ける' },
  { kanji: '花', grade: 1, meaning: { en: 'flower', nl: 'bloem' }, on: 'カ', kun: 'はな' },
  { kanji: '赤', grade: 1, meaning: { en: 'red', nl: 'rood' }, on: 'セキ', kun: 'あか' },
  { kanji: '貝', grade: 1, meaning: { en: 'shellfish', nl: 'schelp' }, on: '', kun: 'かい' },
  { kanji: '学', grade: 1, meaning: { en: 'study', nl: 'leren' }, on: 'ガク', kun: 'まな.ぶ' },
  { kanji: '金', grade: 1, meaning: { en: 'gold, money', nl: 'goud, geld' }, on: 'キン', kun: 'かね' },
  { kanji: '空', grade: 1, meaning: { en: 'sky, empty', nl: 'lucht, leeg' }, on: 'クウ', kun: 'そら' },
  { kanji: '青', grade: 1, meaning: { en: 'blue', nl: 'blauw' }, on: 'セイ', kun: 'あお' },
  { kanji: '林', grade: 1, meaning: { en: 'woods', nl: 'bos' }, on: 'リン', kun: 'はやし' },
  { kanji: '雨', grade: 1, meaning: { en: 'rain', nl: 'regen' }, on: 'ウ', kun: 'あめ' },
  { kanji: '音', grade: 1, meaning: { en: 'sound', nl: 'geluid' }, on: 'オン', kun: 'おと' },
  { kanji: '草', grade: 1, meaning: { en: 'grass', nl: 'gras' }, on: 'ソウ', kun: 'くさ' },
  { kanji: '父', grade: 2, meaning: { en: 'father', nl: 'vader' }, on: 'フ', kun: 'ちち' },
  { kanji: '交', grade: 2, meaning: { en: 'cross, exchange', nl: 'kruisen, uitwisselen' }, on: 'コウ', kun: 'まじ.わる' },
  { kanji: '校', grade: 1, meaning: { en: 'school', nl: 'school' }, on: 'コウ', kun: '' },
  { kanji: '森', grade: 1, meaning: { en: 'forest', nl: 'woud' }, on: 'シン', kun: 'もり' },
  { kanji: '行', grade: 2, meaning: { en: 'go', nl: 'gaan' }, on: 'コウ', kun: 'い.く' },
  { kanji: '新', grade: 2, meaning: { en: 'new', nl: 'nieuw' }, on: 'シン', kun: 'あたら.しい' },
  { kanji: '寺', grade: 2, meaning: { en: 'temple', nl: 'tempel' }, on: 'ジ', kun: 'てら' },
  { kanji: '時', grade: 2, meaning: { en: 'time', nl: 'tijd' }, on: 'ジ', kun: 'とき' },
  { kanji: '会', grade: 2, meaning: { en: 'meet', nl: 'ontmoeten' }, on: 'カイ', kun: 'あ.う' },
  { kanji: '国', grade: 2, meaning: { en: 'country', nl: 'land' }, on: 'コク', kun: 'くに' },
  { kanji: '刀', grade: 2, meaning: { en: 'sword', nl: 'zwaard' }, on: 'トウ', kun: 'かたな' },
  { kanji: '分', grade: 2, meaning: { en: 'divide, minute', nl: 'verdelen, minuut' }, on: 'ブン', kun: 'わ.ける' },
  { kanji: '地', grade: 2, meaning: { en: 'ground', nl: 'bodem, terrein' }, on: 'チ', kun: '' },
  { kanji: '後', grade: 2, meaning: { en: 'after, behind', nl: 'na, achter' }, on: 'ゴ', kun: 'あと' },
  { kanji: '門', grade: 2, meaning: { en: 'gate', nl: 'poort' }, on: 'モン', kun: 'かど' },
  { kanji: '間', grade: 2, meaning: { en: 'interval, between', nl: 'tussen, interval' }, on: 'カン', kun: 'あいだ' },
  { kanji: '同', grade: 2, meaning: { en: 'same', nl: 'hetzelfde' }, on: 'ドウ', kun: 'おな.じ' },
  { kanji: '合', grade: 2, meaning: { en: 'fit, join', nl: 'passen, samen' }, on: 'ゴウ', kun: 'あ.う' },
  { kanji: '聞', grade: 2, meaning: { en: 'hear, listen', nl: 'horen' }, on: 'ブン', kun: 'き.く' },
  { kanji: '社', grade: 2, meaning: { en: 'company, shrine', nl: 'bedrijf, heiligdom' }, on: 'シャ', kun: 'やしろ' },
  { kanji: '場', grade: 2, meaning: { en: 'place', nl: 'plaats' }, on: 'ジョウ', kun: 'ば' },
  { kanji: '自', grade: 2, meaning: { en: 'self, own', nl: 'zelf, eigen' }, on: 'ジ', kun: 'みずか.ら' },
  { kanji: '作', grade: 2, meaning: { en: 'make', nl: 'maken' }, on: 'サク', kun: 'つく.る' },
  { kanji: '市', grade: 2, meaning: { en: 'city, market', nl: 'stad, markt' }, on: 'シ', kun: 'いち' },
  { kanji: '長', grade: 2, meaning: { en: 'long, chief', nl: 'lang, leider' }, on: 'チョウ', kun: 'なが.い' },
  { kanji: '前', grade: 2, meaning: { en: 'front, before', nl: 'voor, voorkant' }, on: 'ゼン', kun: 'まえ' },
  { kanji: '東', grade: 2, meaning: { en: 'east', nl: 'oost' }, on: 'トウ', kun: 'ひがし' },
  { kanji: '方', grade: 2, meaning: { en: 'direction', nl: 'richting' }, on: 'ホウ', kun: 'かた' },
  { kanji: '用', grade: 2, meaning: { en: 'use', nl: 'gebruiken' }, on: 'ヨウ', kun: 'もち.いる' },
  { kanji: '通', grade: 2, meaning: { en: 'pass through', nl: 'doorgaan' }, on: 'ツウ', kun: 'とお.る' },
  { kanji: '首', grade: 2, meaning: { en: 'neck', nl: 'nek' }, on: 'シュ', kun: 'くび' },
  { kanji: '道', grade: 2, meaning: { en: 'road, way', nl: 'weg' }, on: 'ドウ', kun: 'みち' },
  { kanji: '高', grade: 2, meaning: { en: 'high, tall', nl: 'hoog' }, on: 'コウ', kun: 'たか.い' },
  { kanji: '米', grade: 2, meaning: { en: 'rice', nl: 'rijst' }, on: 'ベイ', kun: 'こめ' },
  { kanji: '来', grade: 2, meaning: { en: 'come', nl: 'komen' }, on: 'ライ', kun: 'く.る' },
  { kanji: '家', grade: 2, meaning: { en: 'house, family', nl: 'huis, gezin' }, on: 'カ', kun: 'いえ' },
  { kanji: '内', grade: 2, meaning: { en: 'inside', nl: 'binnenkant' }, on: 'ナイ', kun: 'うち' },
  { kanji: '明', grade: 2, meaning: { en: 'bright', nl: 'helder' }, on: 'メイ', kun: 'あか.るい' },
  { kanji: '当', grade: 2, meaning: { en: 'hit, strike', nl: 'raken, treffen' }, on: 'トウ', kun: 'あ.たる' },
  { kanji: '里', grade: 2, meaning: { en: 'hometown', nl: 'geboortedorp' }, on: 'リ', kun: 'さと' },
  { kanji: '予', grade: 3, meaning: { en: 'beforehand', nl: 'vooraf' }, on: 'ヨ', kun: '' },
  { kanji: '野', grade: 2, meaning: { en: 'field', nl: 'veld' }, on: 'ヤ', kun: 'の' },
  { kanji: '回', grade: 2, meaning: { en: 'times, revolve', nl: 'keer, draaien' }, on: 'カイ', kun: 'まわ.る' },
  { kanji: '言', grade: 2, meaning: { en: 'say', nl: 'zeggen' }, on: 'ゲン', kun: 'い.う' },
  { kanji: '外', grade: 2, meaning: { en: 'outside', nl: 'buiten' }, on: 'ガイ', kun: 'そと' },
  { kanji: '体', grade: 2, meaning: { en: 'body', nl: 'lichaam' }, on: 'タイ', kun: 'からだ' },
  { kanji: '京', grade: 2, meaning: { en: 'capital', nl: 'hoofdstad' }, on: 'キョウ', kun: '' },
  { kanji: '心', grade: 2, meaning: { en: 'heart', nl: 'hart' }, on: 'シン', kun: 'こころ' },
  { kanji: '思', grade: 2, meaning: { en: 'think, feel', nl: 'denken, vinden' }, on: 'シ', kun: 'おも.う' },
  { kanji: '理', grade: 2, meaning: { en: 'reason, logic', nl: 'rede, logica' }, on: 'リ', kun: '' },
  { kanji: '矢', grade: 2, meaning: { en: 'arrow', nl: 'pijl' }, on: 'シ', kun: 'や' },
  { kanji: '知', grade: 2, meaning: { en: 'know', nl: 'weten' }, on: 'チ', kun: 'し.る' },
  { kanji: '今', grade: 2, meaning: { en: 'now', nl: 'nu' }, on: 'コン', kun: 'いま' },
  { kanji: '公', grade: 2, meaning: { en: 'public', nl: 'openbaar' }, on: 'コウ', kun: '' },
  { kanji: '売', grade: 2, meaning: { en: 'sell', nl: 'verkopen' }, on: 'バイ', kun: 'う.る' },
  { kanji: '記', grade: 2, meaning: { en: 'record, note', nl: 'opschrijven' }, on: 'キ', kun: 'しる.す' },
  { kanji: '書', grade: 2, meaning: { en: 'write', nl: 'schrijven' }, on: 'ショ', kun: 'か.く' },
  { kanji: '線', grade: 2, meaning: { en: 'line', nl: 'lijn' }, on: 'セン', kun: '' },
  { kanji: '北', grade: 2, meaning: { en: 'north', nl: 'noord' }, on: 'ホク', kun: 'きた' },
  { kanji: '毎', grade: 2, meaning: { en: 'every', nl: 'elke' }, on: 'マイ', kun: '' },
  { kanji: '海', grade: 2, meaning: { en: 'sea', nl: 'zee' }, on: 'カイ', kun: 'うみ' },
  { kanji: '何', grade: 2, meaning: { en: 'what', nl: 'wat' }, on: 'カ', kun: 'なに' },
  { kanji: '語', grade: 2, meaning: { en: 'language, word', nl: 'taal, woord' }, on: 'ゴ', kun: 'かた.る' },
  { kanji: '朝', grade: 2, meaning: { en: 'morning', nl: 'ochtend' }, on: 'チョウ', kun: 'あさ' },
  { kanji: '原', grade: 2, meaning: { en: 'plain', nl: 'vlakte' }, on: 'ゲン', kun: 'はら' },
  { kanji: '老', grade: 4, meaning: { en: 'aged, elderly', nl: 'bejaard, ouderdom' }, on: 'ロウ', kun: 'お.いる' },
  { kanji: '教', grade: 2, meaning: { en: 'teach', nl: 'onderwijzen' }, on: 'キョウ', kun: 'おし.える' },
  { kanji: '話', grade: 2, meaning: { en: 'talk, story', nl: 'praten, verhaal' }, on: 'ワ', kun: 'はな.す' },
  { kanji: '数', grade: 2, meaning: { en: 'count, figures', nl: 'aantal, tellen' }, on: 'スウ', kun: 'かず' },
  { kanji: '由', grade: 3, meaning: { en: 'cause', nl: 'oorzaak' }, on: 'ユ', kun: 'よし' },
  { kanji: '画', grade: 2, meaning: { en: 'image, stroke', nl: 'beeld, streek' }, on: 'ガ', kun: '' },
  { kanji: '多', grade: 2, meaning: { en: 'many', nl: 'veel' }, on: 'タ', kun: 'おお.い' },
  { kanji: '西', grade: 2, meaning: { en: 'west', nl: 'west' }, on: 'セイ', kun: 'にし' },
  { kanji: '元', grade: 2, meaning: { en: 'beginning, former', nl: 'begin, voormalig' }, on: 'ゲン', kun: 'もと' },
  { kanji: '台', grade: 2, meaning: { en: 'platform', nl: 'platform, standaard' }, on: 'ダイ', kun: '' },
  { kanji: '風', grade: 2, meaning: { en: 'wind', nl: 'wind' }, on: 'フウ', kun: 'かぜ' },
  { kanji: '近', grade: 2, meaning: { en: 'near', nl: 'dichtbij' }, on: 'キン', kun: 'ちか.い' },
  { kanji: '馬', grade: 2, meaning: { en: 'horse', nl: 'paard' }, on: 'バ', kun: 'うま' },
  { kanji: '組', grade: 2, meaning: { en: 'group, assemble', nl: 'groep, samenstellen' }, on: 'ソ', kun: 'く.む' },
  { kanji: '番', grade: 2, meaning: { en: 'number in order', nl: 'beurt, nummer' }, on: 'バン', kun: '' },
  { kanji: '少', grade: 2, meaning: { en: 'few, little', nl: 'weinig' }, on: 'ショウ', kun: 'すこ.し' },
  { kanji: '点', grade: 2, meaning: { en: 'point, dot', nl: 'punt' }, on: 'テン', kun: '' },
  { kanji: '活', grade: 2, meaning: { en: 'lively, activity', nl: 'activiteit' }, on: 'カツ', kun: '' },
  { kanji: '南', grade: 2, meaning: { en: 'south', nl: 'zuid' }, on: 'ナン', kun: 'みなみ' },
  { kanji: '電', grade: 2, meaning: { en: 'electricity', nl: 'elektriciteit' }, on: 'デン', kun: '' },
  { kanji: '考', grade: 2, meaning: { en: 'consider', nl: 'nadenken' }, on: 'コウ', kun: 'かんが.える' },
  { kanji: '読', grade: 2, meaning: { en: 'read', nl: 'lezen' }, on: 'ドク', kun: 'よ.む' },
  { kanji: '形', grade: 2, meaning: { en: 'shape', nl: 'vorm' }, on: 'ケイ', kun: 'かたち' },
  { kanji: '弓', grade: 2, meaning: { en: 'bow', nl: 'boog' }, on: 'キュウ', kun: 'ゆみ' },
  { kanji: '引', grade: 2, meaning: { en: 'pull', nl: 'trekken' }, on: 'イン', kun: 'ひ.く' },
  { kanji: '太', grade: 2, meaning: { en: 'thick, fat', nl: 'dik' }, on: 'タイ', kun: 'ふと.い' },
  { kanji: '万', grade: 2, meaning: { en: '10,000', nl: 'tienduizend' }, on: 'マン', kun: '' },
  { kanji: '楽', grade: 2, meaning: { en: 'fun, music', nl: 'plezier, muziek' }, on: 'ガク', kun: 'たの.しい' },
  { kanji: '直', grade: 2, meaning: { en: 'straight, fix', nl: 'recht, herstellen' }, on: 'チョク', kun: 'なお.す' },
  { kanji: '店', grade: 2, meaning: { en: 'shop', nl: 'winkel' }, on: 'テン', kun: 'みせ' },
  { kanji: '声', grade: 2, meaning: { en: 'voice', nl: 'stem' }, on: 'セイ', kun: 'こえ' },
  { kanji: '計', grade: 2, meaning: { en: 'measure, plan', nl: 'meten, plan' }, on: 'ケイ', kun: 'はか.る' },
  { kanji: '古', grade: 2, meaning: { en: 'old', nl: 'oud' }, on: 'コ', kun: 'ふる.い' },
  { kanji: '強', grade: 2, meaning: { en: 'strong', nl: 'sterk' }, on: 'キョウ', kun: 'つよ.い' },
  { kanji: '広', grade: 2, meaning: { en: 'wide', nl: 'breed' }, on: 'コウ', kun: 'ひろ.い' },
  { kanji: '親', grade: 2, meaning: { en: 'parent', nl: 'ouder' }, on: 'シン', kun: 'おや' },
  { kanji: '科', grade: 2, meaning: { en: 'course, section', nl: 'vak, afdeling' }, on: 'カ', kun: '' },
  { kanji: '切', grade: 2, meaning: { en: 'cut', nl: 'snijden' }, on: 'セツ', kun: 'き.る' },
  { kanji: '欠', grade: 4, meaning: { en: 'lack, absence', nl: 'gebrek, ontbreken' }, on: 'ケツ', kun: 'か.ける' },
  { kanji: '歌', grade: 2, meaning: { en: 'song, sing', nl: 'lied, zingen' }, on: 'カ', kun: 'うた' },
  { kanji: '光', grade: 2, meaning: { en: 'light (shine)', nl: 'licht (schijnsel)' }, on: 'コウ', kun: 'ひかり' },
  { kanji: '戸', grade: 2, meaning: { en: 'door', nl: 'deur' }, on: 'コ', kun: 'と' },
  { kanji: '豆', grade: 3, meaning: { en: 'bean', nl: 'boon' }, on: 'トウ', kun: 'まめ' },
  { kanji: '頭', grade: 2, meaning: { en: 'head', nl: 'hoofd, kop' }, on: 'トウ', kun: 'あたま' },
  { kanji: '食', grade: 2, meaning: { en: 'eat, food', nl: 'eten' }, on: 'ショク', kun: 'た.べる' },
  { kanji: '半', grade: 2, meaning: { en: 'half', nl: 'half' }, on: 'ハン', kun: 'なか.ば' },
  { kanji: '夜', grade: 2, meaning: { en: 'night', nl: 'nacht' }, on: 'ヤ', kun: 'よる' },
  { kanji: '色', grade: 2, meaning: { en: 'colour', nl: 'kleur' }, on: 'ショク', kun: 'いろ' },
  { kanji: '母', grade: 2, meaning: { en: 'mother', nl: 'moeder' }, on: 'ボ', kun: 'はは' },
  { kanji: '衣', grade: 4, meaning: { en: 'garment', nl: 'kledingstuk' }, on: 'イ', kun: 'ころも' },
  { kanji: '園', grade: 2, meaning: { en: 'garden, park', nl: 'tuin, park' }, on: 'エン', kun: 'その' },
  { kanji: '谷', grade: 2, meaning: { en: 'valley', nl: 'vallei' }, on: 'コク', kun: 'たに' },
  { kanji: '帰', grade: 2, meaning: { en: 'return home', nl: 'terugkeren' }, on: 'キ', kun: 'かえ.る' },
  { kanji: '午', grade: 2, meaning: { en: 'midday hour', nl: 'twaalf uur' }, on: 'ゴ', kun: '' },
  { kanji: '顔', grade: 2, meaning: { en: 'face', nl: 'gezicht' }, on: 'ガン', kun: 'かお' },
  { kanji: '室', grade: 2, meaning: { en: 'room', nl: 'kamer' }, on: 'シツ', kun: 'むろ' },
  { kanji: '走', grade: 2, meaning: { en: 'run', nl: 'rennen' }, on: 'ソウ', kun: 'はし.る' },
  { kanji: '船', grade: 2, meaning: { en: 'ship', nl: 'schip' }, on: 'セン', kun: 'ふね' },
  { kanji: '歩', grade: 2, meaning: { en: 'walk', nl: 'lopen' }, on: 'ホ', kun: 'ある.く' },
  { kanji: '星', grade: 2, meaning: { en: 'star', nl: 'ster' }, on: 'セイ', kun: 'ほし' },
  { kanji: '秋', grade: 2, meaning: { en: 'autumn', nl: 'herfst' }, on: 'シュウ', kun: 'あき' },
  { kanji: '黒', grade: 2, meaning: { en: 'black', nl: 'zwart' }, on: 'コク', kun: 'くろ' },
  { kanji: '春', grade: 2, meaning: { en: 'spring', nl: 'lente' }, on: 'シュン', kun: 'はる' },
  { kanji: '氏', grade: 4, meaning: { en: 'surname, lineage', nl: 'achternaam, clan' }, on: 'シ', kun: 'うじ' },
  { kanji: '紙', grade: 2, meaning: { en: 'paper', nl: 'papier' }, on: 'シ', kun: 'かみ' },
  { kanji: '図', grade: 2, meaning: { en: 'diagram, map', nl: 'schema, plattegrond' }, on: 'ズ', kun: 'はか.る' },
  { kanji: '岩', grade: 2, meaning: { en: 'rock', nl: 'rots' }, on: 'ガン', kun: 'いわ' },
  { kanji: '友', grade: 2, meaning: { en: 'friend', nl: 'vriend' }, on: 'ユウ', kun: 'とも' },
  { kanji: '細', grade: 2, meaning: { en: 'thin, fine', nl: 'dun, fijn' }, on: 'サイ', kun: 'ほそ.い' },
  { kanji: '遠', grade: 2, meaning: { en: 'far', nl: 'ver' }, on: 'エン', kun: 'とお.い' },
  { kanji: '角', grade: 2, meaning: { en: 'corner, horn', nl: 'hoek, hoorn' }, on: 'カク', kun: 'かど' },
  { kanji: '羽', grade: 2, meaning: { en: 'feather, wing', nl: 'veer, vleugel' }, on: 'ウ', kun: 'はね' },
  { kanji: '曜', grade: 2, meaning: { en: 'weekday', nl: 'weekdag' }, on: 'ヨウ', kun: '' },
  { kanji: '鳥', grade: 2, meaning: { en: 'bird', nl: 'vogel' }, on: 'チョウ', kun: 'とり' },
  { kanji: '夏', grade: 2, meaning: { en: 'summer', nl: 'zomer' }, on: 'カ', kun: 'なつ' },
  { kanji: '丸', grade: 2, meaning: { en: 'round', nl: 'rond' }, on: 'ガン', kun: 'まる' },
  { kanji: '雪', grade: 2, meaning: { en: 'snow', nl: 'sneeuw' }, on: 'セツ', kun: 'ゆき' },
  { kanji: '兄', grade: 2, meaning: { en: 'older brother', nl: 'oudere broer' }, on: 'ケイ', kun: 'あに' },
  { kanji: '買', grade: 2, meaning: { en: 'buy', nl: 'kopen' }, on: 'バイ', kun: 'か.う' },
  { kanji: '弟', grade: 2, meaning: { en: 'younger brother', nl: 'jongere broer' }, on: 'テイ', kun: 'おとうと' },
  { kanji: '算', grade: 2, meaning: { en: 'calculate', nl: 'rekenen' }, on: 'サン', kun: '' },
  { kanji: '池', grade: 2, meaning: { en: 'pond', nl: 'vijver' }, on: 'チ', kun: 'いけ' },
  { kanji: '周', grade: 4, meaning: { en: 'circumference, lap', nl: 'omtrek, ronde' }, on: 'シュウ', kun: 'まわ.り' },
  { kanji: '週', grade: 2, meaning: { en: 'week', nl: 'week' }, on: 'シュウ', kun: '' },
  { kanji: '絵', grade: 2, meaning: { en: 'drawing', nl: 'tekening' }, on: 'カイ', kun: 'え' },
  { kanji: '肉', grade: 2, meaning: { en: 'meat', nl: 'vlees' }, on: 'ニク', kun: '' },
  { kanji: '答', grade: 2, meaning: { en: 'answer', nl: 'antwoord' }, on: 'トウ', kun: 'こた.える' },
  { kanji: '茶', grade: 2, meaning: { en: 'tea', nl: 'thee' }, on: 'チャ', kun: '' },
  { kanji: '雲', grade: 2, meaning: { en: 'cloud', nl: 'wolk' }, on: 'ウン', kun: 'くも' },
  { kanji: '毛', grade: 2, meaning: { en: 'hair, fur', nl: 'haar, vacht' }, on: 'モウ', kun: 'け' },
  { kanji: '弱', grade: 2, meaning: { en: 'weak', nl: 'zwak' }, on: 'ジャク', kun: 'よわ.い' },
  { kanji: '鳴', grade: 2, meaning: { en: 'cry, chirp', nl: 'klinken, roepen' }, on: 'メイ', kun: 'な.く' },
  { kanji: '姉', grade: 2, meaning: { en: 'older sister', nl: 'oudere zus' }, on: 'シ', kun: 'あね' },
  { kanji: '黄', grade: 2, meaning: { en: 'yellow', nl: 'geel' }, on: 'コウ', kun: 'き' },
  { kanji: '未', grade: 4, meaning: { en: 'yet (to come)', nl: 'toekomstig (nog niet)' }, on: 'ミ', kun: '' },
  { kanji: '妹', grade: 2, meaning: { en: 'younger sister', nl: 'jongere zus' }, on: 'マイ', kun: 'いもうと' },
  { kanji: '冬', grade: 2, meaning: { en: 'winter', nl: 'winter' }, on: 'トウ', kun: 'ふゆ' },
  { kanji: '魚', grade: 2, meaning: { en: 'fish', nl: 'vis' }, on: 'ギョ', kun: 'さかな' },
  { kanji: '牛', grade: 2, meaning: { en: 'cow', nl: 'koe' }, on: 'ギュウ', kun: 'うし' },
  { kanji: '晴', grade: 2, meaning: { en: 'clear weather', nl: 'opklaren' }, on: 'セイ', kun: 'は.れる' },
  { kanji: '才', grade: 2, meaning: { en: 'talent', nl: 'talent' }, on: 'サイ', kun: '' },
  { kanji: '昼', grade: 2, meaning: { en: 'daytime', nl: 'middag, overdag' }, on: 'チュウ', kun: 'ひる' },
  { kanji: '汽', grade: 2, meaning: { en: 'steam', nl: 'stoom' }, on: 'キ', kun: '' },
  { kanji: '麦', grade: 2, meaning: { en: 'wheat', nl: 'tarwe' }, on: 'バク', kun: 'むぎ' },
  { kanji: '事', grade: 3, meaning: { en: 'matter, affair', nl: 'zaak, kwestie' }, on: 'ジ', kun: 'こと' },
  { kanji: '部', grade: 3, meaning: { en: 'part, division', nl: 'deel, onderdeel' }, on: 'ブ', kun: '' },
  { kanji: '者', grade: 3, meaning: { en: 'someone', nl: 'iemand' }, on: 'シャ', kun: 'もの' },
  { kanji: '発', grade: 3, meaning: { en: 'departure, launch', nl: 'vertrek, lancering' }, on: 'ハツ', kun: '' },
  { kanji: '代', grade: 3, meaning: { en: 'substitute', nl: 'vervangen' }, on: 'ダイ', kun: 'か.わる' },
  { kanji: '第', grade: 3, meaning: { en: 'ordinal prefix', nl: 'rangtelwoord' }, on: 'ダイ', kun: '' },
  { kanji: '開', grade: 3, meaning: { en: 'open', nl: 'openen' }, on: 'カイ', kun: 'ひら.く' },
  { kanji: '定', grade: 3, meaning: { en: 'determine', nl: 'bepalen' }, on: 'テイ', kun: 'さだ.める' },
  { kanji: '所', grade: 3, meaning: { en: 'spot, location', nl: 'plek, locatie' }, on: 'ショ', kun: 'ところ' },
  { kanji: '物', grade: 3, meaning: { en: 'thing', nl: 'ding' }, on: 'ブツ', kun: 'もの' },
  { kanji: '羊', grade: 3, meaning: { en: 'sheep', nl: 'schaap' }, on: 'ヨウ', kun: 'ひつじ' },
  { kanji: '業', grade: 3, meaning: { en: 'occupation', nl: 'beroep' }, on: 'ギョウ', kun: 'わざ' },
  { kanji: '県', grade: 3, meaning: { en: 'prefecture', nl: 'prefectuur' }, on: 'ケン', kun: '' },
  { kanji: '対', grade: 3, meaning: { en: 'versus', nl: 'tegenover' }, on: 'タイ', kun: '' },
  { kanji: '重', grade: 3, meaning: { en: 'heavy', nl: 'zwaar' }, on: 'ジュウ', kun: 'おも.い' },
  { kanji: '動', grade: 3, meaning: { en: 'move', nl: 'bewegen' }, on: 'ドウ', kun: 'うご.く' },
  { kanji: '主', grade: 3, meaning: { en: 'master', nl: 'meester' }, on: 'シュ', kun: 'ぬし' },
  { kanji: '全', grade: 3, meaning: { en: 'whole', nl: 'geheel' }, on: 'ゼン', kun: 'まった.く' },
  { kanji: '表', grade: 3, meaning: { en: 'surface', nl: 'oppervlak' }, on: 'ヒョウ', kun: 'おもて' },
  { kanji: '度', grade: 3, meaning: { en: 'degree', nl: 'graad' }, on: 'ド', kun: 'たび' },
  { kanji: '世', grade: 3, meaning: { en: 'world', nl: 'wereld' }, on: 'セ', kun: 'よ' },
  { kanji: '実', grade: 3, meaning: { en: 'fruit', nl: 'vrucht' }, on: 'ジツ', kun: 'み' },
  { kanji: '島', grade: 3, meaning: { en: 'island', nl: 'eiland' }, on: 'トウ', kun: 'しま' },
  { kanji: '平', grade: 3, meaning: { en: 'flat, level', nl: 'plat, effen' }, on: 'ヘイ', kun: 'たい.ら' },
  { kanji: '和', grade: 3, meaning: { en: 'harmony', nl: 'harmonie' }, on: 'ワ', kun: 'やわ.らぐ' },
  { kanji: '取', grade: 3, meaning: { en: 'take', nl: 'nemen' }, on: 'シュ', kun: 'と.る' },
  { kanji: '員', grade: 3, meaning: { en: 'member, staff', nl: 'lid, personeelslid' }, on: 'イン', kun: '' },
  { kanji: '申', grade: 3, meaning: { en: 'report, declare', nl: 'melden, verklaren' }, on: 'シン', kun: 'もう.す' },
  { kanji: '神', grade: 3, meaning: { en: 'god', nl: 'god' }, on: 'シン', kun: 'かみ' },
  { kanji: '勝', grade: 3, meaning: { en: 'win', nl: 'winnen' }, on: 'ショウ', kun: 'か.つ' },
  { kanji: '持', grade: 3, meaning: { en: 'hold', nl: 'vasthouden' }, on: 'ジ', kun: 'も.つ' },
  { kanji: '死', grade: 3, meaning: { en: 'die', nl: 'sterven' }, on: 'シ', kun: 'し.ぬ' },
  { kanji: '送', grade: 3, meaning: { en: 'send', nl: 'sturen' }, on: 'ソウ', kun: 'おく.る' },
  { kanji: '号', grade: 3, meaning: { en: 'issue, edition', nl: 'editie, uitgave' }, on: 'ゴウ', kun: '' },
  { kanji: '放', grade: 3, meaning: { en: 'release', nl: 'loslaten' }, on: 'ホウ', kun: 'はな.す' },
  { kanji: '式', grade: 3, meaning: { en: 'ceremony', nl: 'ceremonie' }, on: 'シキ', kun: '' },
  { kanji: '決', grade: 3, meaning: { en: 'decide', nl: 'beslissen' }, on: 'ケツ', kun: 'き.める' },
  { kanji: '身', grade: 3, meaning: { en: 'physique, stature', nl: 'lijf, gestalte' }, on: 'シン', kun: 'み' },
  { kanji: '相', grade: 3, meaning: { en: 'mutual', nl: 'wederzijds' }, on: 'ソウ', kun: 'あい' },
  { kanji: '意', grade: 3, meaning: { en: 'meaning, intent', nl: 'betekenis, bedoeling' }, on: 'イ', kun: '' },
  { kanji: '面', grade: 3, meaning: { en: 'plane, facet', nl: 'vlak, facet' }, on: 'メン', kun: '' },
  { kanji: '期', grade: 3, meaning: { en: 'period', nl: 'periode' }, on: 'キ', kun: '' },
  { kanji: '受', grade: 3, meaning: { en: 'receive', nl: 'ontvangen' }, on: 'ジュ', kun: 'う.ける' },
  { kanji: '屋', grade: 3, meaning: { en: 'roof', nl: 'dak' }, on: 'オク', kun: 'や' },
  { kanji: '都', grade: 3, meaning: { en: 'metropolis', nl: 'metropool' }, on: 'ト', kun: 'みやこ' },
  { kanji: '駅', grade: 3, meaning: { en: 'station', nl: 'station' }, on: 'エキ', kun: '' },
  { kanji: '区', grade: 3, meaning: { en: 'ward', nl: 'wijk' }, on: 'ク', kun: '' },
  { kanji: '次', grade: 3, meaning: { en: 'next', nl: 'volgende' }, on: 'ジ', kun: 'つぎ' },
  { kanji: '品', grade: 3, meaning: { en: 'goods', nl: 'waren' }, on: 'ヒン', kun: 'しな' },
  { kanji: '使', grade: 3, meaning: { en: 'employ', nl: 'inzetten, benutten' }, on: 'シ', kun: 'つか.う' },
  { kanji: '様', grade: 3, meaning: { en: 'manner', nl: 'manier' }, on: 'ヨウ', kun: 'さま' },
  { kanji: '軍', grade: 4, meaning: { en: 'army', nl: 'leger' }, on: 'グン', kun: 'いくさ' },
  { kanji: '運', grade: 3, meaning: { en: 'carry', nl: 'vervoeren' }, on: 'ウン', kun: 'はこ.ぶ' },
  { kanji: '向', grade: 3, meaning: { en: 'turn toward', nl: 'toewenden, richten' }, on: 'コウ', kun: 'む.かう' },
  { kanji: '曲', grade: 3, meaning: { en: 'melody', nl: 'melodie' }, on: 'キョク', kun: 'ま.がる' },
  { kanji: '等', grade: 3, meaning: { en: 'equal', nl: 'gelijk' }, on: 'トウ', kun: 'ひと.しい' },
  { kanji: '完', grade: 4, meaning: { en: 'completion', nl: 'voltooiing' }, on: 'カン', kun: '' },
  { kanji: '院', grade: 3, meaning: { en: 'institution', nl: 'instituut' }, on: 'イン', kun: '' },
  { kanji: '美', grade: 3, meaning: { en: 'beautiful', nl: 'mooi' }, on: 'ビ', kun: 'うつく.しい' },
  { kanji: '界', grade: 3, meaning: { en: 'boundary', nl: 'grens' }, on: 'カイ', kun: '' },
  { kanji: '有', grade: 3, meaning: { en: 'have', nl: 'hebben' }, on: 'ユウ', kun: 'あ.る' },
  { kanji: '役', grade: 3, meaning: { en: 'role, duty', nl: 'rol, functie' }, on: 'ヤク', kun: '' },
  { kanji: '指', grade: 3, meaning: { en: 'finger', nl: 'vinger' }, on: 'シ', kun: 'ゆび' },
  { kanji: '集', grade: 3, meaning: { en: 'gather', nl: 'verzamelen' }, on: 'シュウ', kun: 'あつ.める' },
  { kanji: '州', grade: 3, meaning: { en: 'province', nl: 'provincie' }, on: 'シュウ', kun: 'す' },
  { kanji: '調', grade: 3, meaning: { en: 'investigate, check', nl: 'nagaan, uitzoeken' }, on: 'チョウ', kun: 'しら.べる' },
  { kanji: '安', grade: 3, meaning: { en: 'cheap', nl: 'goedkoop' }, on: 'アン', kun: 'やす.い' },
  { kanji: '始', grade: 3, meaning: { en: 'start', nl: 'starten' }, on: 'シ', kun: 'はじ.める' },
  { kanji: '進', grade: 3, meaning: { en: 'advance', nl: 'vooruitgaan' }, on: 'シン', kun: 'すす.む' },
  { kanji: '他', grade: 3, meaning: { en: 'other', nl: 'ander' }, on: 'タ', kun: 'ほか' },
  { kanji: '流', grade: 3, meaning: { en: 'flow', nl: 'stromen' }, on: 'リュウ', kun: 'なが.れる' },
  { kanji: '注', grade: 3, meaning: { en: 'pour', nl: 'gieten' }, on: 'チュウ', kun: 'そそ.ぐ' },
  { kanji: '求', grade: 4, meaning: { en: 'seek, demand', nl: 'eisen, zoeken' }, on: 'キュウ', kun: 'もと.める' },
  { kanji: '球', grade: 3, meaning: { en: 'sphere, globe', nl: 'bol, globe' }, on: 'キュウ', kun: 'たま' },
  { kanji: '終', grade: 3, meaning: { en: 'finish', nl: 'eindigen' }, on: 'シュウ', kun: 'お.わる' },
  { kanji: '感', grade: 3, meaning: { en: 'feeling', nl: 'gevoel' }, on: 'カン', kun: '' },
  { kanji: '問', grade: 3, meaning: { en: 'question', nl: 'vraag' }, on: 'モン', kun: 'と.う' },
  { kanji: '各', grade: 4, meaning: { en: 'each', nl: 'elk, ieder' }, on: 'カク', kun: 'おのおの' },
  { kanji: '路', grade: 3, meaning: { en: 'path, route', nl: 'pad, route' }, on: 'ロ', kun: 'じ' },
  { kanji: '具', grade: 3, meaning: { en: 'tool', nl: 'gereedschap' }, on: 'グ', kun: '' },
  { kanji: '真', grade: 3, meaning: { en: 'truth', nl: 'waarheid' }, on: 'シン', kun: 'ま' },
  { kanji: '夫', grade: 4, meaning: { en: 'husband', nl: 'echtgenoot' }, on: 'フ', kun: 'おっと' },
  { kanji: '失', grade: 4, meaning: { en: 'loss, misplace', nl: 'kwijtraken, verlies' }, on: 'シツ', kun: 'うしな.う' },
  { kanji: '鉄', grade: 3, meaning: { en: 'iron', nl: 'ijzer' }, on: 'テツ', kun: '' },
  { kanji: '両', grade: 3, meaning: { en: 'both', nl: 'beide' }, on: 'リョウ', kun: '' },
  { kanji: '葉', grade: 3, meaning: { en: 'leaf, foliage', nl: 'blad, loof' }, on: 'ヨウ', kun: 'は' },
  { kanji: '着', grade: 3, meaning: { en: 'wear', nl: 'aantrekken' }, on: 'チャク', kun: 'き.る' },
  { kanji: '宮', grade: 3, meaning: { en: 'palace', nl: 'paleis' }, on: 'キュウ', kun: 'みや' },
  { kanji: '転', grade: 3, meaning: { en: 'roll', nl: 'rollen' }, on: 'テン', kun: 'ころ.がる' },
  { kanji: '題', grade: 3, meaning: { en: 'topic', nl: 'onderwerp' }, on: 'ダイ', kun: '' },
  { kanji: '起', grade: 3, meaning: { en: 'wake', nl: 'ontwaken' }, on: 'キ', kun: 'お.きる' },
  { kanji: '局', grade: 3, meaning: { en: 'bureau, office', nl: 'bureau, kantoor' }, on: 'キョク', kun: '' },
  { kanji: '官', grade: 4, meaning: { en: 'bureaucrat', nl: 'ambtenaar' }, on: 'カン', kun: '' },
  { kanji: '館', grade: 3, meaning: { en: 'hall, building', nl: 'zaal, gebouw' }, on: 'カン', kun: 'やかた' },
  { kanji: '命', grade: 3, meaning: { en: 'lifespan', nl: 'levensduur' }, on: 'メイ', kun: 'いのち' },
  { kanji: '投', grade: 3, meaning: { en: 'throw', nl: 'gooien' }, on: 'トウ', kun: 'な.げる' },
  { kanji: '登', grade: 3, meaning: { en: 'climb', nl: 'klimmen' }, on: 'トウ', kun: 'のぼ.る' },
  { kanji: '反', grade: 3, meaning: { en: 'oppose, resist', nl: 'tegenwerken, verzet' }, on: 'ハン', kun: 'そ.る' },
  { kanji: '落', grade: 3, meaning: { en: 'fall', nl: 'vallen' }, on: 'ラク', kun: 'お.ちる' },
  { kanji: '福', grade: 3, meaning: { en: 'blessing', nl: 'zegen' }, on: 'フク', kun: '' },
  { kanji: '乗', grade: 3, meaning: { en: 'ride, board', nl: 'instappen, meerijden' }, on: 'ジョウ', kun: 'の.る' },
  { kanji: '打', grade: 3, meaning: { en: 'beat', nl: 'slaan, meppen' }, on: 'ダ', kun: 'う.つ' },
  { kanji: '研', grade: 3, meaning: { en: 'sharpen', nl: 'slijpen' }, on: 'ケン', kun: 'と.ぐ' },
  { kanji: '味', grade: 3, meaning: { en: 'taste', nl: 'smaak' }, on: 'ミ', kun: 'あじ' },
  { kanji: '住', grade: 3, meaning: { en: 'reside', nl: 'wonen' }, on: 'ジュウ', kun: 'す.む' },
  { kanji: '昭', grade: 3, meaning: { en: 'radiant', nl: 'stralend' }, on: 'ショウ', kun: '' },
  { kanji: '急', grade: 3, meaning: { en: 'hurry', nl: 'haasten' }, on: 'キュウ', kun: 'いそ.ぐ' },
  { kanji: '配', grade: 3, meaning: { en: 'distribute', nl: 'uitdelen' }, on: 'ハイ', kun: 'くば.る' },
  { kanji: '究', grade: 3, meaning: { en: 'research', nl: 'onderzoek' }, on: 'キュウ', kun: 'きわ.める' },
  { kanji: '去', grade: 3, meaning: { en: 'depart, past', nl: 'weggaan, verleden' }, on: 'キョ', kun: 'さ.る' },
  { kanji: '橋', grade: 3, meaning: { en: 'bridge', nl: 'brug' }, on: 'キョウ', kun: 'はし' },
  { kanji: '君', grade: 3, meaning: { en: 'you', nl: 'jij' }, on: 'クン', kun: 'きみ' },
  { kanji: '育', grade: 3, meaning: { en: 'nurture', nl: 'opvoeden' }, on: 'イク', kun: 'そだ.てる' },
  { kanji: '病', grade: 3, meaning: { en: 'illness', nl: 'ziekte' }, on: 'ビョウ', kun: 'や.む' },
  { kanji: '助', grade: 3, meaning: { en: 'help', nl: 'helpen' }, on: 'ジョ', kun: 'たす.ける' },
  { kanji: '仕', grade: 3, meaning: { en: 'serve', nl: 'dienen' }, on: 'シ', kun: 'つか.える' },
  { kanji: '横', grade: 3, meaning: { en: 'sideways', nl: 'zijwaarts' }, on: 'オウ', kun: 'よこ' },
  { kanji: '係', grade: 3, meaning: { en: 'attendant (in charge)', nl: 'verantwoordelijke (voor een taak)' }, on: 'ケイ', kun: 'かかり' },
  { kanji: '族', grade: 3, meaning: { en: 'tribe, clan', nl: 'stam, volksgroep' }, on: 'ゾク', kun: '' },
  { kanji: '悪', grade: 3, meaning: { en: 'bad', nl: 'slecht' }, on: 'アク', kun: 'わる.い' },
  { kanji: '想', grade: 3, meaning: { en: 'idea', nl: 'idee' }, on: 'ソウ', kun: '' },
  { kanji: '客', grade: 3, meaning: { en: 'guest', nl: 'gast' }, on: 'キャク', kun: '' },
  { kanji: '追', grade: 3, meaning: { en: 'chase', nl: 'achtervolgen' }, on: 'ツイ', kun: 'お.う' },
  { kanji: '根', grade: 3, meaning: { en: 'root, base', nl: 'wortel, basis' }, on: 'コン', kun: 'ね' },
  { kanji: '消', grade: 3, meaning: { en: 'vanish', nl: 'verdwijnen' }, on: 'ショウ', kun: 'き.える' },
  { kanji: '束', grade: 4, meaning: { en: 'bundle, bouquet', nl: 'bundel, boeket' }, on: 'ソク', kun: 'たば' },
  { kanji: '速', grade: 3, meaning: { en: 'fast', nl: 'snel' }, on: 'ソク', kun: 'はや.い' },
  { kanji: '委', grade: 3, meaning: { en: 'entrust', nl: 'toevertrouwen' }, on: 'イ', kun: 'ゆだ.ねる' },
  { kanji: '返', grade: 3, meaning: { en: 'give back', nl: 'teruggeven' }, on: 'ヘン', kun: 'かえ.す' },
  { kanji: '洋', grade: 3, meaning: { en: 'ocean', nl: 'oceaan' }, on: 'ヨウ', kun: '' },
  { kanji: '商', grade: 3, meaning: { en: 'commerce', nl: 'handel' }, on: 'ショウ', kun: 'あきな.う' },
  { kanji: '皮', grade: 3, meaning: { en: 'skin', nl: 'huid' }, on: 'ヒ', kun: 'かわ' },
  { kanji: '波', grade: 3, meaning: { en: 'wave, ripple', nl: 'golf, deining' }, on: 'ハ', kun: 'なみ' },
  { kanji: '列', grade: 3, meaning: { en: 'row', nl: 'rij' }, on: 'レツ', kun: '' },
  { kanji: '深', grade: 3, meaning: { en: 'deep', nl: 'diep' }, on: 'シン', kun: 'ふか.い' },
  { kanji: '医', grade: 3, meaning: { en: 'doctor', nl: 'dokter' }, on: 'イ', kun: '' },
  { kanji: '負', grade: 3, meaning: { en: 'lose', nl: 'verliezen' }, on: 'フ', kun: 'ま.ける' },
  { kanji: '階', grade: 3, meaning: { en: 'storey', nl: 'verdieping' }, on: 'カイ', kun: '' },
  { kanji: '守', grade: 3, meaning: { en: 'protect', nl: 'beschermen' }, on: 'シュ', kun: 'まも.る' },
  { kanji: '共', grade: 4, meaning: { en: 'together, shared', nl: 'gezamenlijk, gedeeld' }, on: 'キョウ', kun: 'とも' },
  { kanji: '港', grade: 3, meaning: { en: 'harbour', nl: 'haven' }, on: 'コウ', kun: 'みなと' },
  { kanji: '級', grade: 3, meaning: { en: 'rank, class', nl: 'rang, klas' }, on: 'キュウ', kun: '' },
  { kanji: '銀', grade: 3, meaning: { en: 'silver', nl: 'zilver' }, on: 'ギン', kun: '' },
  { kanji: '待', grade: 3, meaning: { en: 'wait', nl: 'wachten' }, on: 'タイ', kun: 'ま.つ' },
  { kanji: '央', grade: 3, meaning: { en: 'midpoint', nl: 'middelpunt' }, on: 'オウ', kun: '' },
  { kanji: '庫', grade: 3, meaning: { en: 'warehouse', nl: 'magazijn' }, on: 'コ', kun: '' },
  { kanji: '旅', grade: 3, meaning: { en: 'travel', nl: 'reizen' }, on: 'リョ', kun: 'たび' },
  { kanji: '苦', grade: 3, meaning: { en: 'bitter, painful', nl: 'bitter, pijnlijk' }, on: 'ク', kun: 'くる.しい' },
  { kanji: '談', grade: 3, meaning: { en: 'discussion', nl: 'gesprek' }, on: 'ダン', kun: '' },
  { kanji: '幸', grade: 3, meaning: { en: 'happiness', nl: 'geluk' }, on: 'コウ', kun: 'しあわ.せ' },
  { kanji: '酒', grade: 3, meaning: { en: 'alcohol, sake', nl: 'drank, sake' }, on: 'シュ', kun: 'さけ' },
  { kanji: '陽', grade: 3, meaning: { en: 'sunshine', nl: 'zonneschijn' }, on: 'ヨウ', kun: '' },
  { kanji: '息', grade: 3, meaning: { en: 'breath', nl: 'adem' }, on: 'ソク', kun: 'いき' },
  { kanji: '坂', grade: 3, meaning: { en: 'slope', nl: 'helling' }, on: 'ハン', kun: 'さか' },
  { kanji: '皿', grade: 3, meaning: { en: 'plate', nl: 'bord, schotel' }, on: '', kun: 'さら' },
  { kanji: '血', grade: 3, meaning: { en: 'blood', nl: 'bloed' }, on: 'ケツ', kun: 'ち' },
  { kanji: '宿', grade: 3, meaning: { en: 'inn, lodging', nl: 'herberg, overnachting' }, on: 'シュク', kun: 'やど' },
  { kanji: '章', grade: 3, meaning: { en: 'chapter', nl: 'hoofdstuk' }, on: 'ショウ', kun: '' },
  { kanji: '岸', grade: 3, meaning: { en: 'shore', nl: 'oever' }, on: 'ガン', kun: 'きし' },
  { kanji: '写', grade: 3, meaning: { en: 'copy', nl: 'kopiëren' }, on: 'シャ', kun: 'うつ.す' },
  { kanji: '服', grade: 3, meaning: { en: 'clothes', nl: 'kleren' }, on: 'フク', kun: '' },
  { kanji: '農', grade: 3, meaning: { en: 'agriculture', nl: 'landbouw' }, on: 'ノウ', kun: '' },
  { kanji: '薬', grade: 3, meaning: { en: 'medicine', nl: 'medicijn' }, on: 'ヤク', kun: 'くすり' },
  { kanji: '板', grade: 3, meaning: { en: 'plank', nl: 'plank' }, on: 'ハン', kun: 'いた' },
  { kanji: '短', grade: 3, meaning: { en: 'short', nl: 'kort' }, on: 'タン', kun: 'みじか.い' },
  { kanji: '習', grade: 3, meaning: { en: 'practise', nl: 'oefenen' }, on: 'シュウ', kun: 'なら.う' },
  { kanji: '温', grade: 3, meaning: { en: 'warm (to touch)', nl: 'warm (aanvoelen)' }, on: 'オン', kun: 'あたた.かい' },
  { kanji: '遊', grade: 3, meaning: { en: 'play', nl: 'spelen' }, on: 'ユウ', kun: 'あそ.ぶ' },
  { kanji: '祭', grade: 3, meaning: { en: 'festival', nl: 'festival' }, on: 'サイ', kun: 'まつ.り' },
  { kanji: '庭', grade: 3, meaning: { en: 'yard, courtyard', nl: 'erf, achtertuin' }, on: 'テイ', kun: 'にわ' },
  { kanji: '暗', grade: 3, meaning: { en: 'dark', nl: 'donker' }, on: 'アン', kun: 'くら.い' },
  { kanji: '軽', grade: 3, meaning: { en: 'light (weight)', nl: 'licht (gewicht)' }, on: 'ケイ', kun: 'かる.い' },
  { kanji: '整', grade: 3, meaning: { en: 'arrange', nl: 'ordenen' }, on: 'セイ', kun: 'ととの.える' },
  { kanji: '植', grade: 3, meaning: { en: 'plant', nl: 'planten' }, on: 'ショク', kun: 'う.える' },
  { kanji: '詩', grade: 3, meaning: { en: 'poem', nl: 'gedicht' }, on: 'シ', kun: '' },
  { kanji: '飲', grade: 3, meaning: { en: 'drink', nl: 'drinken' }, on: 'イン', kun: 'の.む' },
  { kanji: '筆', grade: 3, meaning: { en: 'brush', nl: 'penseel' }, on: 'ヒツ', kun: 'ふで' },
  { kanji: '悲', grade: 3, meaning: { en: 'sad', nl: 'verdrietig' }, on: 'ヒ', kun: 'かな.しい' },
  { kanji: '練', grade: 3, meaning: { en: 'train, drill', nl: 'trainen, drillen' }, on: 'レン', kun: 'ね.る' },
  { kanji: '礼', grade: 3, meaning: { en: 'courtesy', nl: 'beleefdheid' }, on: 'レイ', kun: '' },
  { kanji: '油', grade: 3, meaning: { en: 'oil', nl: 'olie' }, on: 'ユ', kun: 'あぶら' },
  { kanji: '秒', grade: 3, meaning: { en: 'second', nl: 'seconde' }, on: 'ビョウ', kun: '' },
  { kanji: '倍', grade: 3, meaning: { en: 'double', nl: 'dubbel' }, on: 'バイ', kun: '' },
  { kanji: '湯', grade: 3, meaning: { en: 'hot (water)', nl: 'heet (water)' }, on: 'トウ', kun: 'ゆ' },
  { kanji: '湖', grade: 3, meaning: { en: 'lake', nl: 'meer, plas' }, on: 'コ', kun: 'みずうみ' },
  { kanji: '漢', grade: 3, meaning: { en: 'Chinese', nl: 'Chinees' }, on: 'カン', kun: '' },
  { kanji: '荷', grade: 3, meaning: { en: 'luggage', nl: 'bagage' }, on: 'カ', kun: 'に' },
  { kanji: '昔', grade: 3, meaning: { en: 'olden days (long ago)', nl: 'vroeger (lang geleden)' }, on: 'セキ', kun: 'むかし' },
  { kanji: '童', grade: 3, meaning: { en: 'youngster, juvenile', nl: 'jochie, ventje' }, on: 'ドウ', kun: 'わらべ' },
  { kanji: '箱', grade: 3, meaning: { en: 'box', nl: 'doos' }, on: '', kun: 'はこ' },
  { kanji: '寒', grade: 3, meaning: { en: 'cold (weather)', nl: 'koud (weer)' }, on: 'カン', kun: 'さむ.い' },
  { kanji: '緑', grade: 3, meaning: { en: 'green', nl: 'groen' }, on: 'リョク', kun: 'みどり' },
  { kanji: '歯', grade: 3, meaning: { en: 'tooth', nl: 'tand' }, on: 'シ', kun: 'は' },
  { kanji: '鼻', grade: 3, meaning: { en: 'nose', nl: 'neus' }, on: 'ビ', kun: 'はな' },
  { kanji: '畑', grade: 3, meaning: { en: 'cropland, farmland', nl: 'akker, bouwland' }, on: '', kun: 'はたけ' },
  { kanji: '氷', grade: 3, meaning: { en: 'ice', nl: 'ijs' }, on: 'ヒョウ', kun: 'こおり' },
  { kanji: '帳', grade: 3, meaning: { en: 'notebook', nl: 'schrift, notitieboek' }, on: 'チョウ', kun: '' },
  { kanji: '柱', grade: 3, meaning: { en: 'pillar', nl: 'pilaar' }, on: 'チュウ', kun: 'はしら' },
  { kanji: '炭', grade: 3, meaning: { en: 'charcoal', nl: 'houtskool' }, on: 'タン', kun: 'すみ' },
  { kanji: '泳', grade: 3, meaning: { en: 'swim', nl: 'zwemmen' }, on: 'エイ', kun: 'およ.ぐ' },
  { kanji: '勉', grade: 3, meaning: { en: 'diligence, effort', nl: 'ijver, toewijding' }, on: 'ベン', kun: '' },
  { kanji: '暑', grade: 3, meaning: { en: 'hot (weather)', nl: 'heet (weer)' }, on: 'ショ', kun: 'あつ.い' },
  { kanji: '拾', grade: 3, meaning: { en: 'retrieve', nl: 'oprapen' }, on: 'シュウ', kun: 'ひろ.う' },
  { kanji: '笛', grade: 3, meaning: { en: 'flute', nl: 'fluit' }, on: 'テキ', kun: 'ふえ' },
  { kanji: '単', grade: 4, meaning: { en: 'single, simple', nl: 'enkelvoudig, simpel' }, on: 'タン', kun: '' },
  { kanji: '戦', grade: 4, meaning: { en: 'war, battle', nl: 'oorlog, strijd' }, on: 'セン', kun: 'たたか.う' },
  { kanji: '的', grade: 4, meaning: { en: 'target', nl: 'doelwit' }, on: 'テキ', kun: 'まと' },
  { kanji: '関', grade: 4, meaning: { en: 'barrier, connection', nl: 'barrière, verband' }, on: 'カン', kun: 'せき' },
  { kanji: '成', grade: 4, meaning: { en: 'become', nl: 'worden' }, on: 'セイ', kun: 'な.る' },
  { kanji: '選', grade: 4, meaning: { en: 'choose, elect', nl: 'kiezen, verkiezen' }, on: 'セン', kun: 'えら.ぶ' },
  { kanji: '連', grade: 4, meaning: { en: 'link, accompany', nl: 'schakel, meenemen' }, on: 'レン', kun: 'つら.なる' },
  { kanji: '最', grade: 4, meaning: { en: 'most, utmost', nl: 'meest, uiterst' }, on: 'サイ', kun: 'もっと.も' },
  { kanji: '以', grade: 4, meaning: { en: 'from (a point on)', nl: 'vanaf (een punt)' }, on: 'イ', kun: 'もっ.て' },
  { kanji: '初', grade: 4, meaning: { en: 'first (time)', nl: 'eerste (keer)' }, on: 'ショ', kun: 'はじ.め' },
  { kanji: '法', grade: 4, meaning: { en: 'law, method', nl: 'wet, methode' }, on: 'ホウ', kun: '' },
  { kanji: '機', grade: 4, meaning: { en: 'machine, opportunity', nl: 'machine, gelegenheid' }, on: 'キ', kun: '' },
  { kanji: '信', grade: 4, meaning: { en: 'trust, believe', nl: 'vertrouwen, geloven' }, on: 'シン', kun: '' },
  { kanji: '不', grade: 4, meaning: { en: 'not, non-', nl: 'niet, on-' }, on: 'フ', kun: '' },
  { kanji: '民', grade: 4, meaning: { en: 'people (populace)', nl: 'volk' }, on: 'ミン', kun: 'たみ' },
  { kanji: '議', grade: 4, meaning: { en: 'deliberate, debate', nl: 'vergaderen, debat' }, on: 'ギ', kun: '' },
  { kanji: '位', grade: 4, meaning: { en: 'position, standing', nl: 'positie' }, on: 'イ', kun: 'くらい' },
  { kanji: '無', grade: 4, meaning: { en: 'without, nil', nl: 'zonder, niets' }, on: 'ム', kun: 'な.い' },
  { kanji: '結', grade: 4, meaning: { en: 'tie, bind', nl: 'knopen, binden' }, on: 'ケツ', kun: 'むす.ぶ' },
  { kanji: '加', grade: 4, meaning: { en: 'add', nl: 'toevoegen, optellen' }, on: 'カ', kun: 'くわ.える' },
  { kanji: '要', grade: 4, meaning: { en: 'need, essential', nl: 'nodig, kern' }, on: 'ヨウ', kun: 'い.る' },
  { kanji: '産', grade: 4, meaning: { en: 'produce, childbirth', nl: 'voortbrengen, bevalling' }, on: 'サン', kun: 'う.む' },
  { kanji: '特', grade: 4, meaning: { en: 'special', nl: 'speciaal, bijzonder' }, on: 'トク', kun: '' },
  { kanji: '治', grade: 4, meaning: { en: 'govern, heal', nl: 'genezen, besturen' }, on: 'ジ', kun: 'おさ.める' },
  { kanji: '置', grade: 4, meaning: { en: 'put down', nl: 'neerzetten' }, on: 'チ', kun: 'お.く' },
  { kanji: '付', grade: 4, meaning: { en: 'attach, affix', nl: 'vastmaken, bijvoegen' }, on: 'フ', kun: 'つ.ける' },
  { kanji: '変', grade: 4, meaning: { en: 'change, strange', nl: 'wijziging, vreemd' }, on: 'ヘン', kun: 'か.わる' },
  { kanji: '続', grade: 4, meaning: { en: 'continue', nl: 'voortzetten, vervolgen' }, on: 'ゾク', kun: 'つづ.く' },
  { kanji: '約', grade: 4, meaning: { en: 'promise, roughly', nl: 'belofte, ongeveer' }, on: 'ヤク', kun: '' },
  { kanji: '別', grade: 4, meaning: { en: 'separate, another', nl: 'apart, gescheiden' }, on: 'ベツ', kun: 'わか.れる' },
  { kanji: '参', grade: 4, meaning: { en: 'participate', nl: 'deelnemen' }, on: 'サン', kun: 'まい.る' },
  { kanji: '典', grade: 4, meaning: { en: 'compendium, canon', nl: 'naslagwerk, canon' }, on: 'テン', kun: '' },
  { kanji: '利', grade: 4, meaning: { en: 'profit, advantage', nl: 'voordeel, winst' }, on: 'リ', kun: 'き.く' },
  { kanji: '井', grade: 4, meaning: { en: 'well (water)', nl: 'put' }, on: 'セイ', kun: 'い' },
  { kanji: '録', grade: 4, meaning: { en: 'register, transcript', nl: 'registreren, opname' }, on: 'ロク', kun: '' },
  { kanji: '岡', grade: 4, meaning: { en: 'hill', nl: 'heuvel' }, on: 'コウ', kun: 'おか' },
  { kanji: '伝', grade: 4, meaning: { en: 'transmit, convey', nl: 'overbrengen, doorgeven' }, on: 'デン', kun: 'つた.える' },
  { kanji: '説', grade: 4, meaning: { en: 'theory, explain', nl: 'theorie, uitleggen' }, on: 'セツ', kun: 'と.く' },
  { kanji: '松', grade: 4, meaning: { en: 'pine', nl: 'den, pijnboom' }, on: 'ショウ', kun: 'まつ' },
  { kanji: '達', grade: 4, meaning: { en: 'attain, reach', nl: 'bereiken' }, on: 'タツ', kun: '' },
  { kanji: '試', grade: 4, meaning: { en: 'try, attempt', nl: 'proberen, poging' }, on: 'シ', kun: 'こころ.みる' },
  { kanji: '果', grade: 4, meaning: { en: 'outcome, result', nl: 'uitkomst, resultaat' }, on: 'カ', kun: 'は.たす' },
  { kanji: '阪', grade: 4, meaning: { en: 'hillside (Osaka)', nl: 'glooiing (Osaka)' }, on: 'ハン', kun: 'さか' },
  { kanji: '改', grade: 4, meaning: { en: 'revise, renew', nl: 'herzien, vernieuwen' }, on: 'カイ', kun: 'あらた.める' },
  { kanji: '府', grade: 4, meaning: { en: 'metropolitan district', nl: 'stadsprefectuur' }, on: 'フ', kun: '' },
  { kanji: '愛', grade: 4, meaning: { en: 'love', nl: 'liefde' }, on: 'アイ', kun: 'いと.しい' },
  { kanji: '然', grade: 4, meaning: { en: 'so, as such', nl: 'zo, zodanig' }, on: 'ゼン', kun: '' },
  { kanji: '英', grade: 4, meaning: { en: 'England', nl: 'Engeland' }, on: 'エイ', kun: 'はなぶさ' },
  { kanji: '隊', grade: 4, meaning: { en: 'squad, unit', nl: 'eenheid, ploeg' }, on: 'タイ', kun: '' },
  { kanji: '建', grade: 4, meaning: { en: 'build, erect', nl: 'bouwen' }, on: 'ケン', kun: 'た.てる' },
  { kanji: '種', grade: 4, meaning: { en: 'seed, kind', nl: 'zaad, soort' }, on: 'シュ', kun: 'たね' },
  { kanji: '兵', grade: 4, meaning: { en: 'soldier', nl: 'soldaat' }, on: 'ヘイ', kun: '' },
  { kanji: '挙', grade: 4, meaning: { en: 'raise', nl: 'opsteken (hand)' }, on: 'キョ', kun: 'あ.げる' },
  { kanji: '害', grade: 4, meaning: { en: 'harm, damage', nl: 'schade, letsel' }, on: 'ガイ', kun: '' },
  { kanji: '競', grade: 4, meaning: { en: 'compete, rival', nl: 'wedijveren, concurreren' }, on: 'キョウ', kun: 'きそ.う' },
  { kanji: '城', grade: 4, meaning: { en: 'castle', nl: 'kasteel' }, on: 'ジョウ', kun: 'しろ' },
  { kanji: '協', grade: 4, meaning: { en: 'cooperate', nl: 'samenwerken' }, on: 'キョウ', kun: '' },
  { kanji: '崎', grade: 4, meaning: { en: 'cape (coast)', nl: 'kaap (kust)' }, on: 'キ', kun: 'さき' },
  { kanji: '料', grade: 4, meaning: { en: 'fee, charge', nl: 'tarief, vergoeding' }, on: 'リョウ', kun: '' },
  { kanji: '観', grade: 4, meaning: { en: 'view, outlook', nl: 'uitzicht, aanblik' }, on: 'カン', kun: 'み.る' },
  { kanji: '念', grade: 4, meaning: { en: 'thought (kept in mind)', nl: 'gedachte (in het achterhoofd)' }, on: 'ネン', kun: '' },
  { kanji: '側', grade: 4, meaning: { en: 'side, flank', nl: 'zijkant, flank' }, on: 'ソク', kun: 'がわ' },
  { kanji: '陸', grade: 4, meaning: { en: 'dry land', nl: 'vasteland' }, on: 'リク', kun: '' },
  { kanji: '佐', grade: 4, meaning: { en: 'assistant', nl: 'assistent' }, on: 'サ', kun: '' },
  { kanji: '良', grade: 4, meaning: { en: 'good', nl: 'goed' }, on: 'リョウ', kun: 'よ.い' },
  { kanji: '好', grade: 4, meaning: { en: 'like, fondness', nl: 'houden van, voorliefde' }, on: 'コウ', kun: 'この.む' },
  { kanji: '飛', grade: 4, meaning: { en: 'fly', nl: 'vliegen' }, on: 'ヒ', kun: 'と.ぶ' },
  { kanji: '残', grade: 4, meaning: { en: 'remain, leftover', nl: 'overblijven, rest' }, on: 'ザン', kun: 'のこ.る' },
  { kanji: '必', grade: 4, meaning: { en: 'surely, must', nl: 'beslist, zeker' }, on: 'ヒツ', kun: 'かなら.ず' },
  { kanji: '例', grade: 4, meaning: { en: 'example, precedent', nl: 'voorbeeld, precedent' }, on: 'レイ', kun: 'たと.える' },
  { kanji: '管', grade: 4, meaning: { en: 'pipe, tube', nl: 'buis, pijp' }, on: 'カン', kun: 'くだ' },
  { kanji: '郡', grade: 4, meaning: { en: 'county', nl: 'district' }, on: 'グン', kun: '' },
  { kanji: '省', grade: 4, meaning: { en: 'ministry, omit', nl: 'ministerie, weglaten' }, on: 'セイ', kun: 'はぶ.く' },
  { kanji: '類', grade: 4, meaning: { en: 'category, genus', nl: 'categorie, genre' }, on: 'ルイ', kun: 'たぐ.い' },
  { kanji: '察', grade: 4, meaning: { en: 'presume, infer', nl: 'vermoeden, aanvoelen' }, on: 'サツ', kun: '' },
  { kanji: '争', grade: 4, meaning: { en: 'quarrel, dispute', nl: 'ruzie, geschil' }, on: 'ソウ', kun: 'あらそ.う' },
  { kanji: '票', grade: 4, meaning: { en: 'ballot, vote', nl: 'stembiljet' }, on: 'ヒョウ', kun: '' },
  { kanji: '験', grade: 4, meaning: { en: 'exam, test', nl: 'examen, test' }, on: 'ケン', kun: '' },
  { kanji: '器', grade: 4, meaning: { en: 'tableware, instrument', nl: 'servies, instrument' }, on: 'キ', kun: 'うつわ' },
  { kanji: '笑', grade: 4, meaning: { en: 'laugh', nl: 'lachen' }, on: 'ショウ', kun: 'わら.う' },
  { kanji: '児', grade: 4, meaning: { en: 'infant, toddler', nl: 'kleuter, zuigeling' }, on: 'ジ', kun: '' },
  { kanji: '芸', grade: 4, meaning: { en: 'art, performance', nl: 'kunst, optreden' }, on: 'ゲイ', kun: '' },
  { kanji: '博', grade: 4, meaning: { en: 'erudition', nl: 'geleerdheid' }, on: 'ハク', kun: '' },
  { kanji: '案', grade: 4, meaning: { en: 'proposal, draft', nl: 'voorstel, ontwerp' }, on: 'アン', kun: 'つくえ' },
  { kanji: '敗', grade: 4, meaning: { en: 'defeat, failure', nl: 'nederlaag, mislukking' }, on: 'ハイ', kun: 'やぶ.れる' },
  { kanji: '末', grade: 4, meaning: { en: 'end', nl: 'einde' }, on: 'マツ', kun: 'すえ' },
  { kanji: '司', grade: 4, meaning: { en: 'preside, administer', nl: 'beheren, leiden' }, on: 'シ', kun: 'つかさど.る' },
  { kanji: '量', grade: 4, meaning: { en: 'quantity, amount', nl: 'hoeveelheid' }, on: 'リョウ', kun: 'はか.る' },
  { kanji: '富', grade: 4, meaning: { en: 'wealth', nl: 'rijkdom' }, on: 'フ', kun: 'と.む' },
  { kanji: '覚', grade: 4, meaning: { en: 'memorize', nl: 'onthouden' }, on: 'カク', kun: 'おぼ.える' },
  { kanji: '清', grade: 4, meaning: { en: 'pure, cleanse', nl: 'zuiver, reinigen' }, on: 'セイ', kun: 'きよ.い' },
  { kanji: '帯', grade: 4, meaning: { en: 'belt, zone', nl: 'gordel, zone' }, on: 'タイ', kun: 'お.びる' },
  { kanji: '差', grade: 4, meaning: { en: 'difference, margin', nl: 'verschil, marge' }, on: 'サ', kun: 'さ.す' },
  { kanji: '令', grade: 4, meaning: { en: 'command, decree', nl: 'bevel, decreet' }, on: 'レイ', kun: '' },
  { kanji: '候', grade: 4, meaning: { en: 'climate', nl: 'klimaat' }, on: 'コウ', kun: '' },
  { kanji: '辺', grade: 4, meaning: { en: 'vicinity, edge', nl: 'omgeving, rand' }, on: 'ヘン', kun: 'あた.り' },
  { kanji: '望', grade: 4, meaning: { en: 'hope', nl: 'hoop, verlangen' }, on: 'ボウ', kun: 'のぞ.む' },
  { kanji: '奈', grade: 4, meaning: { en: 'Nara (name use)', nl: 'Nara (in namen)' }, on: 'ナ', kun: '' },
  { kanji: '徳', grade: 4, meaning: { en: 'virtue', nl: 'deugd' }, on: 'トク', kun: '' },
  { kanji: '働', grade: 4, meaning: { en: 'work', nl: 'werken' }, on: 'ドウ', kun: 'はたら.く' },
  { kanji: '満', grade: 4, meaning: { en: 'full, satisfied', nl: 'vol, verzadigd' }, on: 'マン', kun: 'み.ちる' },
  { kanji: '席', grade: 4, meaning: { en: 'seat', nl: 'zitplaats' }, on: 'セキ', kun: '' },
  { kanji: '極', grade: 4, meaning: { en: 'extreme, pole', nl: 'uiterste, pool' }, on: 'キョク', kun: 'きわ.める' },
  { kanji: '香', grade: 4, meaning: { en: 'fragrance', nl: 'geur' }, on: 'コウ', kun: 'か' },
  { kanji: '熱', grade: 4, meaning: { en: 'heat, fever', nl: 'hitte, koorts' }, on: 'ネツ', kun: 'あつ.い' },
  { kanji: '低', grade: 4, meaning: { en: 'low', nl: 'laag' }, on: 'テイ', kun: 'ひく.い' },
  { kanji: '静', grade: 4, meaning: { en: 'quiet, still', nl: 'stil, rustig' }, on: 'セイ', kun: 'しず.か' },
  { kanji: '労', grade: 4, meaning: { en: 'labour, toil', nl: 'arbeid, moeite' }, on: 'ロウ', kun: '' },
  { kanji: '賀', grade: 4, meaning: { en: 'congratulations', nl: 'gelukwens' }, on: 'ガ', kun: '' },
  { kanji: '便', grade: 4, meaning: { en: 'convenience, mail', nl: 'gemak, post' }, on: 'ベン', kun: 'たよ.り' },
  { kanji: '鹿', grade: 4, meaning: { en: 'deer', nl: 'hert' }, on: 'ロク', kun: 'しか' },
  { kanji: '倉', grade: 4, meaning: { en: 'storehouse, granary', nl: 'schuur, graanschuur' }, on: 'ソウ', kun: 'くら' },
  { kanji: '健', grade: 4, meaning: { en: 'healthy', nl: 'gezond' }, on: 'ケン', kun: 'すこ.やか' },
  { kanji: '徒', grade: 4, meaning: { en: 'pupil, disciple', nl: 'leerling, volgeling' }, on: 'ト', kun: '' },
  { kanji: '積', grade: 4, meaning: { en: 'stack, accumulate', nl: 'opstapelen, ophopen' }, on: 'セキ', kun: 'つ.む' },
  { kanji: '街', grade: 4, meaning: { en: 'avenue', nl: 'winkelstraat' }, on: 'ガイ', kun: 'まち' },
  { kanji: '臣', grade: 4, meaning: { en: 'vassal, minister', nl: 'vazal, minister' }, on: 'シン', kun: '' },
  { kanji: '輪', grade: 4, meaning: { en: 'ring, hoop', nl: 'ring, hoepel' }, on: 'リン', kun: 'わ' },
  { kanji: '照', grade: 4, meaning: { en: 'illuminate', nl: 'beschijnen, verlichten' }, on: 'ショウ', kun: 'て.る' },
  { kanji: '給', grade: 4, meaning: { en: 'supply, salary', nl: 'verstrekken, loon' }, on: 'キュウ', kun: '' },
  { kanji: '億', grade: 4, meaning: { en: '100 million', nl: '100 miljoen' }, on: 'オク', kun: '' },
  { kanji: '散', grade: 4, meaning: { en: 'scatter', nl: 'verstrooien' }, on: 'サン', kun: 'ち.る' },
  { kanji: '辞', grade: 4, meaning: { en: 'resign, expression', nl: 'aftreden, uitdrukking' }, on: 'ジ', kun: 'や.める' },
  { kanji: '養', grade: 4, meaning: { en: 'foster, rear', nl: 'grootbrengen, verzorgen' }, on: 'ヨウ', kun: 'やしな.う' },
  { kanji: '材', grade: 4, meaning: { en: 'timber, material', nl: 'timmerhout, materiaal' }, on: 'ザイ', kun: '' },
  { kanji: '卒', grade: 4, meaning: { en: 'graduate', nl: 'afstuderen' }, on: 'ソツ', kun: '' },
  { kanji: '沖', grade: 4, meaning: { en: 'offshore (out at sea)', nl: 'buitengaats (op open zee)' }, on: 'チュウ', kun: 'おき' },
  { kanji: '課', grade: 4, meaning: { en: 'lesson, task', nl: 'les, taak' }, on: 'カ', kun: '' },
  { kanji: '群', grade: 4, meaning: { en: 'flock, herd', nl: 'kudde, zwerm' }, on: 'グン', kun: 'む.れる' },
  { kanji: '景', grade: 4, meaning: { en: 'scenery', nl: 'landschap' }, on: 'ケイ', kun: '' },
  { kanji: '標', grade: 4, meaning: { en: 'signpost, marker', nl: 'wegwijzer, merkteken' }, on: 'ヒョウ', kun: '' },
  { kanji: '折', grade: 4, meaning: { en: 'fold, snap', nl: 'vouwen, knakken' }, on: 'セツ', kun: 'お.る' },
  { kanji: '功', grade: 4, meaning: { en: 'success, merit', nl: 'succes, verdienste' }, on: 'コウ', kun: 'いさお' },
  { kanji: '順', grade: 4, meaning: { en: 'sequence, obedient', nl: 'volgorde, gehoorzaam' }, on: 'ジュン', kun: '' },
  { kanji: '仲', grade: 4, meaning: { en: 'relationship', nl: 'verstandhouding' }, on: 'チュウ', kun: 'なか' },
  { kanji: '節', grade: 4, meaning: { en: 'joint, verse', nl: 'knoop (bamboe), couplet' }, on: 'セツ', kun: 'ふし' },
  { kanji: '底', grade: 4, meaning: { en: 'bottom, sole', nl: 'onderkant' }, on: 'テイ', kun: 'そこ' },
  { kanji: '印', grade: 4, meaning: { en: 'stamp, seal', nl: 'stempel, zegel' }, on: 'イン', kun: 'しるし' },
  { kanji: '康', grade: 4, meaning: { en: 'wellbeing', nl: 'welzijn' }, on: 'コウ', kun: '' },
  { kanji: '焼', grade: 4, meaning: { en: 'bake, grill', nl: 'bakken, roosteren' }, on: 'ショウ', kun: 'や.く' },
  { kanji: '札', grade: 4, meaning: { en: 'tag, banknote', nl: 'kaartje, bankbiljet' }, on: 'サツ', kun: 'ふだ' },
  { kanji: '熊', grade: 4, meaning: { en: 'bear', nl: 'beer' }, on: 'ユウ', kun: 'くま' },
  { kanji: '願', grade: 4, meaning: { en: 'wish, plea', nl: 'wens, verzoek' }, on: 'ガン', kun: 'ねが.う' },
  { kanji: '縄', grade: 4, meaning: { en: 'rope', nl: 'touw' }, on: 'ジョウ', kun: 'なわ' },
  { kanji: '冷', grade: 4, meaning: { en: 'cold (touch), chill', nl: 'koud (aanraking), kil' }, on: 'レイ', kun: 'つめ.たい' },
  { kanji: '副', grade: 4, meaning: { en: 'deputy', nl: 'plaatsvervanger' }, on: 'フク', kun: '' },
  { kanji: '栄', grade: 4, meaning: { en: 'flourish, glory', nl: 'bloei, glorie' }, on: 'エイ', kun: 'さか.える' },
  { kanji: '梅', grade: 4, meaning: { en: 'plum', nl: 'pruim' }, on: 'バイ', kun: 'うめ' },
  { kanji: '固', grade: 4, meaning: { en: 'solid, harden', nl: 'stevig, verharden' }, on: 'コ', kun: 'かた.める' },
  { kanji: '希', grade: 4, meaning: { en: 'scarce', nl: 'schaars, zeldzaam' }, on: 'キ', kun: 'まれ' },
  { kanji: '昨', grade: 4, meaning: { en: 'yesterday', nl: 'gisteren' }, on: 'サク', kun: '' },
  { kanji: '季', grade: 4, meaning: { en: 'season', nl: 'seizoen' }, on: 'キ', kun: '' },
  { kanji: '牧', grade: 4, meaning: { en: 'pasture, graze', nl: 'weide, hoeden' }, on: 'ボク', kun: 'まき' },
  { kanji: '貨', grade: 4, meaning: { en: 'freight, currency', nl: 'vracht, valuta' }, on: 'カ', kun: 'たから' },
  { kanji: '浅', grade: 4, meaning: { en: 'shallow', nl: 'ondiep' }, on: 'セン', kun: 'あさ.い' },
  { kanji: '飯', grade: 4, meaning: { en: 'meal', nl: 'maaltijd' }, on: 'ハン', kun: 'めし' },
  { kanji: '岐', grade: 4, meaning: { en: 'fork (road)', nl: 'splitsing (weg)' }, on: 'キ', kun: '' },
  { kanji: '埼', grade: 4, meaning: { en: 'cape (place names)', nl: 'kaap (plaatsnamen)' }, on: 'キ', kun: 'さき' },
  { kanji: '泣', grade: 4, meaning: { en: 'weep', nl: 'huilen' }, on: 'キュウ', kun: 'な.く' },
  { kanji: '勇', grade: 4, meaning: { en: 'courage, brave', nl: 'moed, dapper' }, on: 'ユウ', kun: 'いさ.む' },
  { kanji: '潟', grade: 4, meaning: { en: 'lagoon', nl: 'lagune, wad' }, on: 'セキ', kun: 'かた' },
  { kanji: '包', grade: 4, meaning: { en: 'wrap', nl: 'inpakken, omhullen' }, on: 'ホウ', kun: 'つつ.む' },
  { kanji: '孫', grade: 4, meaning: { en: 'grandchild', nl: 'kleinkind' }, on: 'ソン', kun: 'まご' },
  { kanji: '鏡', grade: 4, meaning: { en: 'mirror', nl: 'spiegel' }, on: 'キョウ', kun: 'かがみ' },
  { kanji: '灯', grade: 4, meaning: { en: 'lamp', nl: 'lamp' }, on: 'トウ', kun: '' },
  { kanji: '唱', grade: 4, meaning: { en: 'chant, recite', nl: 'opzeggen, voordragen' }, on: 'ショウ', kun: 'とな.える' },
  { kanji: '旗', grade: 4, meaning: { en: 'flag', nl: 'vlag' }, on: 'キ', kun: 'はた' },
  { kanji: '塩', grade: 4, meaning: { en: 'salt', nl: 'zout' }, on: 'エン', kun: 'しお' },
  { kanji: '借', grade: 4, meaning: { en: 'borrow', nl: 'lenen' }, on: 'シャク', kun: 'か.りる' },
  { kanji: '訓', grade: 4, meaning: { en: 'kun reading, precept', nl: 'kun-lezing, leerregel' }, on: 'クン', kun: '' },
  { kanji: '祝', grade: 4, meaning: { en: 'celebrate', nl: 'vieren' }, on: 'シュク', kun: 'いわ.う' },
  { kanji: '梨', grade: 4, meaning: { en: 'pear', nl: 'peer' }, on: 'リ', kun: 'なし' },
  { kanji: '漁', grade: 4, meaning: { en: 'fishing', nl: 'visserij' }, on: 'ギョ', kun: 'あさ.る' },
  { kanji: '阜', grade: 4, meaning: { en: 'mound (Gifu)', nl: 'terp (Gifu)' }, on: 'フ', kun: '' },
  { kanji: '菜', grade: 4, meaning: { en: 'vegetable, greens', nl: 'groente' }, on: 'サイ', kun: 'な' },
  { kanji: '努', grade: 4, meaning: { en: 'strive, exert', nl: 'streven, inspanning' }, on: 'ド', kun: 'つと.める' },
  { kanji: '浴', grade: 4, meaning: { en: 'bathe', nl: 'baden' }, on: 'ヨク', kun: 'あ.びる' },
  { kanji: '械', grade: 4, meaning: { en: 'apparatus, contraption', nl: 'werktuig, mechaniek' }, on: 'カイ', kun: 'かせ' },
  { kanji: '茨', grade: 4, meaning: { en: 'thorn, briar', nl: 'doorn, braamstruik' }, on: 'シ', kun: 'いばら' },
  { kanji: '栃', grade: 4, meaning: { en: 'chestnut (Tochigi)', nl: 'kastanje (Tochigi)' }, on: '', kun: 'とち' },
  { kanji: '滋', grade: 4, meaning: { en: 'nourishing', nl: 'voedzaam' }, on: 'ジ', kun: '' },
  { kanji: '刷', grade: 4, meaning: { en: 'print', nl: 'drukken, afdruk' }, on: 'サツ', kun: 'す.る' },
  { kanji: '兆', grade: 4, meaning: { en: 'omen, trillion', nl: 'voorteken, biljoen' }, on: 'チョウ', kun: 'きざ.し' },
  { kanji: '巣', grade: 4, meaning: { en: 'nest, den', nl: 'nest, hol' }, on: 'ソウ', kun: 'す' },
  { kanji: '径', grade: 4, meaning: { en: 'diameter', nl: 'doorsnede' }, on: 'ケイ', kun: '' },
  { kanji: '媛', grade: 4, meaning: { en: 'princess', nl: 'prinses' }, on: 'エン', kun: 'ひめ' },
  { kanji: '芽', grade: 4, meaning: { en: 'bud, sprout', nl: 'knop, scheut' }, on: 'ガ', kun: 'め' },
];
