import strokeData from '../assets/data/kanji/strokes.json';

/**
 * The stroke data is generated by tools/build-stroke-data.mjs, which fails
 * loudly on a bad character. These are the guards for the file that is actually
 * shipped, so a hand-edit or a half-finished regeneration cannot slip through.
 */
describe('the shipped stroke data', () => {
  it('has the whole deck: all three school years, in full', () => {
    expect(strokeData.characters).toHaveLength(440);
    expect(strokeData.characters.filter(c => c.grade === 1)).toHaveLength(80);
    expect(strokeData.characters.filter(c => c.grade === 2)).toHaveLength(160);
    expect(strokeData.characters.filter(c => c.grade === 3)).toHaveLength(200);
    expect(strokeData.viewBox).toBe(109);
  });

  /**
   * The deck is in learning order: nobody should be asked to write 休 before
   * having written 人 and 木. Components come from KanjiVG's decomposition,
   * limited to kanji the deck itself teaches.
   */
  it('teaches every kanji after the parts it is built from', () => {
    const position = new Map(strokeData.characters.map((character, index) => [character.kanji, index]));

    const misplaced = strokeData.characters.flatMap(character =>
      character.components
        .filter(part => (position.get(part) ?? Infinity) > (position.get(character.kanji) ?? 0))
        .map(part => `${character.kanji} before its part ${part}`),
    );

    expect(misplaced).toEqual([]);
  });

  it('has every kanji only once', () => {
    const kanji = strokeData.characters.map(character => character.kanji);

    expect(new Set(kanji).size).toBe(kanji.length);
  });

  it('numbers every stroke of every kanji', () => {
    const mismatched = strokeData.characters
      .filter(character => character.numbers.length !== character.strokes.length)
      .map(character => character.kanji);

    expect(mismatched).toEqual([]);
  });

  it('keeps every stroke number inside the square', () => {
    const outside = strokeData.characters
      .flatMap(character => character.numbers.map(number => ({ kanji: character.kanji, ...number })))
      .filter(number => number.x < 0 || number.x > 109 || number.y < 0 || number.y > 109);

    expect(outside).toEqual([]);
  });

  it('has a meaning in both languages and at least one stroke', () => {
    for (const character of strokeData.characters) {
      expect(character.strokes.length).toBeGreaterThan(0);
      expect(character.meaning.en).toBeTruthy();
      expect(character.meaning.nl).toBeTruthy();
    }
  });

  /**
   * A review shows the meaning and asks for the character, so two kanji may
   * never lay claim to the same word: asked for "grond", a learner who wrote 土
   * cannot be told 地 was wanted. Only the family words survive, because they
   * are never alone - "oudere broer" and "oudere zus" still name one kanji each.
   */
  it('never gives the same meaning to two kanji', () => {
    const qualified = ['older', 'younger', 'brother', 'sister', 'oudere', 'jongere', 'broer', 'zus'];

    for (const language of ['en', 'nl'] as const) {
      const claims = new Map<string, string[]>();
      for (const character of strokeData.characters) {
        for (const word of character.meaning[language].toLowerCase().split(/[,\s]+/).filter(Boolean)) {
          claims.set(word, [...(claims.get(word) ?? []), character.kanji]);
        }
      }

      const shared = [...claims]
        .filter(([word, kanji]) => kanji.length > 1 && !qualified.includes(word))
        .map(([word, kanji]) => `${word}: ${kanji.join(' ')}`);

      expect(shared).toEqual([]);
    }
  });

  it('credits KanjiVG, whose licence asks for it', () => {
    expect(strokeData.source).toBe('KanjiVG');
    expect(strokeData.license).toBe('CC BY-SA 3.0');
  });
});
