import strokeData from '../assets/data/kanji/strokes.json';

/**
 * The stroke data is generated by tools/build-stroke-data.mjs, which fails
 * loudly on a bad character. These are the guards for the file that is actually
 * shipped, so a hand-edit or a half-finished regeneration cannot slip through.
 */
describe('the shipped stroke data', () => {
  it('has the whole deck: all three school years, in full', () => {
    expect(strokeData.characters).toHaveLength(440);
    expect(strokeData.characters.filter(c => c.grade === 1)).toHaveLength(80);
    expect(strokeData.characters.filter(c => c.grade === 2)).toHaveLength(160);
    expect(strokeData.characters.filter(c => c.grade === 3)).toHaveLength(200);
    expect(strokeData.viewBox).toBe(109);
  });

  /**
   * The deck is in learning order: nobody should be asked to write 休 before
   * having written 人 and 木. Components come from KanjiVG's decomposition,
   * limited to kanji the deck itself teaches.
   */
  it('teaches every kanji after the parts it is built from', () => {
    const position = new Map(strokeData.characters.map((character, index) => [character.kanji, index]));

    const misplaced = strokeData.characters.flatMap(character =>
      character.components
        .filter(part => (position.get(part) ?? Infinity) > (position.get(character.kanji) ?? 0))
        .map(part => `${character.kanji} before its part ${part}`),
    );

    expect(misplaced).toEqual([]);
  });

  it('has every kanji only once', () => {
    const kanji = strokeData.characters.map(character => character.kanji);

    expect(new Set(kanji).size).toBe(kanji.length);
  });

  it('numbers every stroke of every kanji', () => {
    const mismatched = strokeData.characters
      .filter(character => character.numbers.length !== character.strokes.length)
      .map(character => character.kanji);

    expect(mismatched).toEqual([]);
  });

  it('keeps every stroke number inside the square', () => {
    const outside = strokeData.characters
      .flatMap(character => character.numbers.map(number => ({ kanji: character.kanji, ...number })))
      .filter(number => number.x < 0 || number.x > 109 || number.y < 0 || number.y > 109);

    expect(outside).toEqual([]);
  });

  /**
   * The ranks the practice list can be sorted by. A missing JLPT level is a
   * fact about the lists - they skip a few kanji - but the skipped ones are
   * known by name, so a regeneration that quietly loses the levels cannot
   * pass as one that found four gaps.
   */
  it('carries a JLPT level for every kanji the lists have', () => {
    const outside = strokeData.characters
      .filter(character => character.jlpt === null)
      .map(character => character.kanji);

    expect(outside).toEqual(['分', '里', '身', '畑']);
    for (const character of strokeData.characters) {
      if (character.jlpt !== null) {
        expect(character.jlpt).toBeGreaterThanOrEqual(1);
        expect(character.jlpt).toBeLessThanOrEqual(5);
      }
    }
  });

  /**
   * Every kanji of the first three school years is common enough to hold a
   * newspaper frequency rank; kanji added later may fall outside KANJIDIC2's
   * 2501 ranked and go null. A rank is a position, so no two kanji share one.
   */
  it('ranks every kanji by frequency, each rank its own', () => {
    const ranks = strokeData.characters.map(character => character.freq);

    expect(ranks.every(rank => Number.isInteger(rank) && rank >= 1)).toBe(true);
    expect(new Set(ranks).size).toBe(ranks.length);
  });

  it('has a meaning in both languages and at least one stroke', () => {
    for (const character of strokeData.characters) {
      expect(character.strokes.length).toBeGreaterThan(0);
      expect(character.meaning.en).toBeTruthy();
      expect(character.meaning.nl).toBeTruthy();
    }
  });

  /**
   * A review shows the meaning and asks for the character, so two kanji may
   * never lay claim to the same word: asked for "grond", a learner who wrote 土
   * cannot be told 地 was wanted.
   *
   * A word in brackets is not a claim but the sense the word is being used in,
   * which is how one word can serve two kanji: "licht (gewicht)" is 軽 and
   * "licht (schijnsel)" is 光, and neither is answerable by the other. So a
   * shared word passes only when every kanji claiming it says which sense it
   * means, and no two of them say the same. The family words survive as they
   * are, because they are never alone - "oudere broer" and "oudere zus" still
   * name one kanji each.
   */
  it('never gives the same meaning to two kanji', () => {
    const family = ['older', 'younger', 'brother', 'sister', 'oudere', 'jongere', 'broer', 'zus'];

    for (const language of ['en', 'nl'] as const) {
      const claims = new Map<string, { kanji: string; sense: string }[]>();
      for (const character of strokeData.characters) {
        for (const phrase of character.meaning[language].toLowerCase().split(',')) {
          const sense = /\(([^)]*)\)/.exec(phrase)?.[1] ?? '';
          for (const word of phrase.replace(/\([^)]*\)/g, '').split(/\s+/).filter(Boolean)) {
            claims.set(word, [...(claims.get(word) ?? []), { kanji: character.kanji, sense }]);
          }
        }
      }

      const shared = [...claims]
        .filter(([word, claimants]) => claimants.length > 1 && !family.includes(word))
        .filter(
          ([, claimants]) =>
            claimants.some(claimant => !claimant.sense) ||
            new Set(claimants.map(claimant => claimant.sense)).size < claimants.length,
        )
        .map(([word, claimants]) =>
          `${word}: ${claimants.map(({ kanji, sense }) => (sense ? `${kanji} (${sense})` : kanji)).join(' ')}`,
        );

      expect(shared).toEqual([]);
    }
  });

  it('credits KanjiVG, whose licence asks for it', () => {
    expect(strokeData.source).toBe('KanjiVG');
    expect(strokeData.license).toBe('CC BY-SA 3.0');
  });
});
