import strokeData from '../assets/data/kanji/strokes.json';

/**
 * The stroke data is generated by tools/build-stroke-data.mjs, which fails
 * loudly on a bad character. These are the guards for the file that is actually
 * shipped, so a hand-edit or a half-finished regeneration cannot slip through.
 */
describe('the shipped stroke data', () => {
  it('has the whole deck: both school years, in full', () => {
    expect(strokeData.characters).toHaveLength(240);
    expect(strokeData.characters.filter(c => c.grade === 1)).toHaveLength(80);
    expect(strokeData.characters.filter(c => c.grade === 2)).toHaveLength(160);
    expect(strokeData.viewBox).toBe(109);
  });

  it('has every kanji only once', () => {
    const kanji = strokeData.characters.map(character => character.kanji);

    expect(new Set(kanji).size).toBe(kanji.length);
  });

  it('numbers every stroke of every kanji', () => {
    const mismatched = strokeData.characters
      .filter(character => character.numbers.length !== character.strokes.length)
      .map(character => character.kanji);

    expect(mismatched).toEqual([]);
  });

  it('keeps every stroke number inside the square', () => {
    const outside = strokeData.characters
      .flatMap(character => character.numbers.map(number => ({ kanji: character.kanji, ...number })))
      .filter(number => number.x < 0 || number.x > 109 || number.y < 0 || number.y > 109);

    expect(outside).toEqual([]);
  });

  it('has a meaning in both languages and at least one stroke', () => {
    for (const character of strokeData.characters) {
      expect(character.strokes.length).toBeGreaterThan(0);
      expect(character.meaning.en).toBeTruthy();
      expect(character.meaning.nl).toBeTruthy();
    }
  });

  it('credits KanjiVG, whose licence asks for it', () => {
    expect(strokeData.source).toBe('KanjiVG');
    expect(strokeData.license).toBe('CC BY-SA 3.0');
  });
});
